ALTER TABLE sites ADD COLUMN proxy_enabled BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE sites ADD COLUMN proxy_host TEXT NOT NULL DEFAULT '127.0.0.1';
ALTER TABLE sites ADD COLUMN proxy_port INTEGER NOT NULL DEFAULT 0;
