// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/agent/v1/agent.proto

package agentv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceActionType int32

const (
	ServiceActionType_SERVICE_ACTION_UNSPECIFIED ServiceActionType = 0
	ServiceActionType_SERVICE_ACTION_START       ServiceActionType = 1
	ServiceActionType_SERVICE_ACTION_STOP        ServiceActionType = 2
	ServiceActionType_SERVICE_ACTION_RESTART     ServiceActionType = 3
	ServiceActionType_SERVICE_ACTION_ENABLE      ServiceActionType = 4
	ServiceActionType_SERVICE_ACTION_DISABLE     ServiceActionType = 5
	ServiceActionType_SERVICE_ACTION_RELOAD      ServiceActionType = 6
)

var ServiceActionType_name = map[int32]string{
	0: "SERVICE_ACTION_UNSPECIFIED",
	1: "SERVICE_ACTION_START",
	2: "SERVICE_ACTION_STOP",
	3: "SERVICE_ACTION_RESTART",
	4: "SERVICE_ACTION_ENABLE",
	5: "SERVICE_ACTION_DISABLE",
	6: "SERVICE_ACTION_RELOAD",
}

var ServiceActionType_value = map[string]int32{
	"SERVICE_ACTION_UNSPECIFIED": 0,
	"SERVICE_ACTION_START":       1,
	"SERVICE_ACTION_STOP":        2,
	"SERVICE_ACTION_RESTART":     3,
	"SERVICE_ACTION_ENABLE":      4,
	"SERVICE_ACTION_DISABLE":     5,
	"SERVICE_ACTION_RELOAD":      6,
}

func (x ServiceActionType) String() string {
	return proto.EnumName(ServiceActionType_name, int32(x))
}

func (ServiceActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{0}
}

type NginxSiteAction int32

const (
	NginxSiteAction_NGINX_SITE_ACTION_UNSPECIFIED NginxSiteAction = 0
	NginxSiteAction_NGINX_SITE_ACTION_UPSERT      NginxSiteAction = 1
	NginxSiteAction_NGINX_SITE_ACTION_DELETE      NginxSiteAction = 2
	NginxSiteAction_NGINX_SITE_ACTION_ENABLE      NginxSiteAction = 3
	NginxSiteAction_NGINX_SITE_ACTION_DISABLE     NginxSiteAction = 4
)

var NginxSiteAction_name = map[int32]string{
	0: "NGINX_SITE_ACTION_UNSPECIFIED",
	1: "NGINX_SITE_ACTION_UPSERT",
	2: "NGINX_SITE_ACTION_DELETE",
	3: "NGINX_SITE_ACTION_ENABLE",
	4: "NGINX_SITE_ACTION_DISABLE",
}

var NginxSiteAction_value = map[string]int32{
	"NGINX_SITE_ACTION_UNSPECIFIED": 0,
	"NGINX_SITE_ACTION_UPSERT":      1,
	"NGINX_SITE_ACTION_DELETE":      2,
	"NGINX_SITE_ACTION_ENABLE":      3,
	"NGINX_SITE_ACTION_DISABLE":     4,
}

func (x NginxSiteAction) String() string {
	return proto.EnumName(NginxSiteAction_name, int32(x))
}

func (NginxSiteAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{1}
}

type FirewallAction int32

const (
	FirewallAction_FIREWALL_ACTION_UNSPECIFIED FirewallAction = 0
	FirewallAction_FIREWALL_ACTION_ALLOW       FirewallAction = 1
	FirewallAction_FIREWALL_ACTION_DENY        FirewallAction = 2
	FirewallAction_FIREWALL_ACTION_DELETE      FirewallAction = 3
)

var FirewallAction_name = map[int32]string{
	0: "FIREWALL_ACTION_UNSPECIFIED",
	1: "FIREWALL_ACTION_ALLOW",
	2: "FIREWALL_ACTION_DENY",
	3: "FIREWALL_ACTION_DELETE",
}

var FirewallAction_value = map[string]int32{
	"FIREWALL_ACTION_UNSPECIFIED": 0,
	"FIREWALL_ACTION_ALLOW":       1,
	"FIREWALL_ACTION_DENY":        2,
	"FIREWALL_ACTION_DELETE":      3,
}

func (x FirewallAction) String() string {
	return proto.EnumName(FirewallAction_name, int32(x))
}

func (FirewallAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{2}
}

type ServiceActionRequest struct {
	ServiceName          string            `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action               ServiceActionType `protobuf:"varint,2,opt,name=action,proto3,enum=agent.v1.ServiceActionType" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServiceActionRequest) Reset()         { *m = ServiceActionRequest{} }
func (m *ServiceActionRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceActionRequest) ProtoMessage()    {}
func (*ServiceActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{0}
}

func (m *ServiceActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceActionRequest.Unmarshal(m, b)
}
func (m *ServiceActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceActionRequest.Marshal(b, m, deterministic)
}
func (m *ServiceActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceActionRequest.Merge(m, src)
}
func (m *ServiceActionRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceActionRequest.Size(m)
}
func (m *ServiceActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceActionRequest proto.InternalMessageInfo

func (m *ServiceActionRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceActionRequest) GetAction() ServiceActionType {
	if m != nil {
		return m.Action
	}
	return ServiceActionType_SERVICE_ACTION_UNSPECIFIED
}

type ServiceActionResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceActionResponse) Reset()         { *m = ServiceActionResponse{} }
func (m *ServiceActionResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceActionResponse) ProtoMessage()    {}
func (*ServiceActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{1}
}

func (m *ServiceActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceActionResponse.Unmarshal(m, b)
}
func (m *ServiceActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceActionResponse.Marshal(b, m, deterministic)
}
func (m *ServiceActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceActionResponse.Merge(m, src)
}
func (m *ServiceActionResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceActionResponse.Size(m)
}
func (m *ServiceActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceActionResponse proto.InternalMessageInfo

func (m *ServiceActionResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ServiceActionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ServiceStatusRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceStatusRequest) Reset()         { *m = ServiceStatusRequest{} }
func (m *ServiceStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceStatusRequest) ProtoMessage()    {}
func (*ServiceStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{2}
}

func (m *ServiceStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatusRequest.Unmarshal(m, b)
}
func (m *ServiceStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatusRequest.Marshal(b, m, deterministic)
}
func (m *ServiceStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatusRequest.Merge(m, src)
}
func (m *ServiceStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceStatusRequest.Size(m)
}
func (m *ServiceStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatusRequest proto.InternalMessageInfo

func (m *ServiceStatusRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type ServiceStatusResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Active               bool     `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	Enabled              bool     `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SubState             string   `protobuf:"bytes,4,opt,name=sub_state,json=subState,proto3" json:"sub_state,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceStatusResponse) Reset()         { *m = ServiceStatusResponse{} }
func (m *ServiceStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceStatusResponse) ProtoMessage()    {}
func (*ServiceStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{3}
}

func (m *ServiceStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceStatusResponse.Unmarshal(m, b)
}
func (m *ServiceStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceStatusResponse.Marshal(b, m, deterministic)
}
func (m *ServiceStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceStatusResponse.Merge(m, src)
}
func (m *ServiceStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceStatusResponse.Size(m)
}
func (m *ServiceStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceStatusResponse proto.InternalMessageInfo

func (m *ServiceStatusResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceStatusResponse) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *ServiceStatusResponse) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ServiceStatusResponse) GetSubState() string {
	if m != nil {
		return m.SubState
	}
	return ""
}

func (m *ServiceStatusResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ServiceLogsRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Lines                int32    `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceLogsRequest) Reset()         { *m = ServiceLogsRequest{} }
func (m *ServiceLogsRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceLogsRequest) ProtoMessage()    {}
func (*ServiceLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{4}
}

func (m *ServiceLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceLogsRequest.Unmarshal(m, b)
}
func (m *ServiceLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceLogsRequest.Marshal(b, m, deterministic)
}
func (m *ServiceLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceLogsRequest.Merge(m, src)
}
func (m *ServiceLogsRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceLogsRequest.Size(m)
}
func (m *ServiceLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceLogsRequest proto.InternalMessageInfo

func (m *ServiceLogsRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceLogsRequest) GetLines() int32 {
	if m != nil {
		return m.Lines
	}
	return 0
}

type LogLine struct {
	Line                 string   `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogLine) Reset()         { *m = LogLine{} }
func (m *LogLine) String() string { return proto.CompactTextString(m) }
func (*LogLine) ProtoMessage()    {}
func (*LogLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{5}
}

func (m *LogLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogLine.Unmarshal(m, b)
}
func (m *LogLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogLine.Marshal(b, m, deterministic)
}
func (m *LogLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogLine.Merge(m, src)
}
func (m *LogLine) XXX_Size() int {
	return xxx_messageInfo_LogLine.Size(m)
}
func (m *LogLine) XXX_DiscardUnknown() {
	xxx_messageInfo_LogLine.DiscardUnknown(m)
}

var xxx_messageInfo_LogLine proto.InternalMessageInfo

func (m *LogLine) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *LogLine) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type CommandExecuteRequest struct {
	Command              string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandExecuteRequest) Reset()         { *m = CommandExecuteRequest{} }
func (m *CommandExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*CommandExecuteRequest) ProtoMessage()    {}
func (*CommandExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{6}
}

func (m *CommandExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandExecuteRequest.Unmarshal(m, b)
}
func (m *CommandExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandExecuteRequest.Marshal(b, m, deterministic)
}
func (m *CommandExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandExecuteRequest.Merge(m, src)
}
func (m *CommandExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_CommandExecuteRequest.Size(m)
}
func (m *CommandExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandExecuteRequest proto.InternalMessageInfo

func (m *CommandExecuteRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandExecuteRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type CommandExecuteResponse struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout               string   `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               string   `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandExecuteResponse) Reset()         { *m = CommandExecuteResponse{} }
func (m *CommandExecuteResponse) String() string { return proto.CompactTextString(m) }
func (*CommandExecuteResponse) ProtoMessage()    {}
func (*CommandExecuteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{7}
}

func (m *CommandExecuteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandExecuteResponse.Unmarshal(m, b)
}
func (m *CommandExecuteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandExecuteResponse.Marshal(b, m, deterministic)
}
func (m *CommandExecuteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandExecuteResponse.Merge(m, src)
}
func (m *CommandExecuteResponse) XXX_Size() int {
	return xxx_messageInfo_CommandExecuteResponse.Size(m)
}
func (m *CommandExecuteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandExecuteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandExecuteResponse proto.InternalMessageInfo

func (m *CommandExecuteResponse) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *CommandExecuteResponse) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *CommandExecuteResponse) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

type PackageRequest struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageRequest) Reset()         { *m = PackageRequest{} }
func (m *PackageRequest) String() string { return proto.CompactTextString(m) }
func (*PackageRequest) ProtoMessage()    {}
func (*PackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{8}
}

func (m *PackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageRequest.Unmarshal(m, b)
}
func (m *PackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageRequest.Marshal(b, m, deterministic)
}
func (m *PackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageRequest.Merge(m, src)
}
func (m *PackageRequest) XXX_Size() int {
	return xxx_messageInfo_PackageRequest.Size(m)
}
func (m *PackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PackageRequest proto.InternalMessageInfo

func (m *PackageRequest) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

type PackageOutput struct {
	Line                 string   `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	IsErr                bool     `protobuf:"varint,2,opt,name=is_err,json=isErr,proto3" json:"is_err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageOutput) Reset()         { *m = PackageOutput{} }
func (m *PackageOutput) String() string { return proto.CompactTextString(m) }
func (*PackageOutput) ProtoMessage()    {}
func (*PackageOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{9}
}

func (m *PackageOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageOutput.Unmarshal(m, b)
}
func (m *PackageOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageOutput.Marshal(b, m, deterministic)
}
func (m *PackageOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageOutput.Merge(m, src)
}
func (m *PackageOutput) XXX_Size() int {
	return xxx_messageInfo_PackageOutput.Size(m)
}
func (m *PackageOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageOutput.DiscardUnknown(m)
}

var xxx_messageInfo_PackageOutput proto.InternalMessageInfo

func (m *PackageOutput) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *PackageOutput) GetIsErr() bool {
	if m != nil {
		return m.IsErr
	}
	return false
}

type PackageStatusResponse struct {
	Installed            bool     `protobuf:"varint,1,opt,name=installed,proto3" json:"installed,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PackageStatusResponse) Reset()         { *m = PackageStatusResponse{} }
func (m *PackageStatusResponse) String() string { return proto.CompactTextString(m) }
func (*PackageStatusResponse) ProtoMessage()    {}
func (*PackageStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{10}
}

func (m *PackageStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PackageStatusResponse.Unmarshal(m, b)
}
func (m *PackageStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PackageStatusResponse.Marshal(b, m, deterministic)
}
func (m *PackageStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackageStatusResponse.Merge(m, src)
}
func (m *PackageStatusResponse) XXX_Size() int {
	return xxx_messageInfo_PackageStatusResponse.Size(m)
}
func (m *PackageStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PackageStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PackageStatusResponse proto.InternalMessageInfo

func (m *PackageStatusResponse) GetInstalled() bool {
	if m != nil {
		return m.Installed
	}
	return false
}

func (m *PackageStatusResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type FileReadRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReadRequest) Reset()         { *m = FileReadRequest{} }
func (m *FileReadRequest) String() string { return proto.CompactTextString(m) }
func (*FileReadRequest) ProtoMessage()    {}
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{11}
}

func (m *FileReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReadRequest.Unmarshal(m, b)
}
func (m *FileReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReadRequest.Marshal(b, m, deterministic)
}
func (m *FileReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReadRequest.Merge(m, src)
}
func (m *FileReadRequest) XXX_Size() int {
	return xxx_messageInfo_FileReadRequest.Size(m)
}
func (m *FileReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileReadRequest proto.InternalMessageInfo

func (m *FileReadRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type FileReadResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileReadResponse) Reset()         { *m = FileReadResponse{} }
func (m *FileReadResponse) String() string { return proto.CompactTextString(m) }
func (*FileReadResponse) ProtoMessage()    {}
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{12}
}

func (m *FileReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileReadResponse.Unmarshal(m, b)
}
func (m *FileReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileReadResponse.Marshal(b, m, deterministic)
}
func (m *FileReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileReadResponse.Merge(m, src)
}
func (m *FileReadResponse) XXX_Size() int {
	return xxx_messageInfo_FileReadResponse.Size(m)
}
func (m *FileReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileReadResponse proto.InternalMessageInfo

func (m *FileReadResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type FileWriteRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Mode                 uint32   `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileWriteRequest) Reset()         { *m = FileWriteRequest{} }
func (m *FileWriteRequest) String() string { return proto.CompactTextString(m) }
func (*FileWriteRequest) ProtoMessage()    {}
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{13}
}

func (m *FileWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileWriteRequest.Unmarshal(m, b)
}
func (m *FileWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileWriteRequest.Marshal(b, m, deterministic)
}
func (m *FileWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileWriteRequest.Merge(m, src)
}
func (m *FileWriteRequest) XXX_Size() int {
	return xxx_messageInfo_FileWriteRequest.Size(m)
}
func (m *FileWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileWriteRequest proto.InternalMessageInfo

func (m *FileWriteRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileWriteRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *FileWriteRequest) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type FileWriteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileWriteResponse) Reset()         { *m = FileWriteResponse{} }
func (m *FileWriteResponse) String() string { return proto.CompactTextString(m) }
func (*FileWriteResponse) ProtoMessage()    {}
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{14}
}

func (m *FileWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileWriteResponse.Unmarshal(m, b)
}
func (m *FileWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileWriteResponse.Marshal(b, m, deterministic)
}
func (m *FileWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileWriteResponse.Merge(m, src)
}
func (m *FileWriteResponse) XXX_Size() int {
	return xxx_messageInfo_FileWriteResponse.Size(m)
}
func (m *FileWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileWriteResponse proto.InternalMessageInfo

func (m *FileWriteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type FileDeleteRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDeleteRequest) Reset()         { *m = FileDeleteRequest{} }
func (m *FileDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*FileDeleteRequest) ProtoMessage()    {}
func (*FileDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{15}
}

func (m *FileDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDeleteRequest.Unmarshal(m, b)
}
func (m *FileDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDeleteRequest.Marshal(b, m, deterministic)
}
func (m *FileDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDeleteRequest.Merge(m, src)
}
func (m *FileDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_FileDeleteRequest.Size(m)
}
func (m *FileDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileDeleteRequest proto.InternalMessageInfo

func (m *FileDeleteRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type FileDeleteResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileDeleteResponse) Reset()         { *m = FileDeleteResponse{} }
func (m *FileDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*FileDeleteResponse) ProtoMessage()    {}
func (*FileDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{16}
}

func (m *FileDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDeleteResponse.Unmarshal(m, b)
}
func (m *FileDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDeleteResponse.Marshal(b, m, deterministic)
}
func (m *FileDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDeleteResponse.Merge(m, src)
}
func (m *FileDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_FileDeleteResponse.Size(m)
}
func (m *FileDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileDeleteResponse proto.InternalMessageInfo

func (m *FileDeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DirCreateRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode                 uint32   `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirCreateRequest) Reset()         { *m = DirCreateRequest{} }
func (m *DirCreateRequest) String() string { return proto.CompactTextString(m) }
func (*DirCreateRequest) ProtoMessage()    {}
func (*DirCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{17}
}

func (m *DirCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirCreateRequest.Unmarshal(m, b)
}
func (m *DirCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirCreateRequest.Marshal(b, m, deterministic)
}
func (m *DirCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirCreateRequest.Merge(m, src)
}
func (m *DirCreateRequest) XXX_Size() int {
	return xxx_messageInfo_DirCreateRequest.Size(m)
}
func (m *DirCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DirCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DirCreateRequest proto.InternalMessageInfo

func (m *DirCreateRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DirCreateRequest) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type DirCreateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirCreateResponse) Reset()         { *m = DirCreateResponse{} }
func (m *DirCreateResponse) String() string { return proto.CompactTextString(m) }
func (*DirCreateResponse) ProtoMessage()    {}
func (*DirCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{18}
}

func (m *DirCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirCreateResponse.Unmarshal(m, b)
}
func (m *DirCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirCreateResponse.Marshal(b, m, deterministic)
}
func (m *DirCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirCreateResponse.Merge(m, src)
}
func (m *DirCreateResponse) XXX_Size() int {
	return xxx_messageInfo_DirCreateResponse.Size(m)
}
func (m *DirCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DirCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DirCreateResponse proto.InternalMessageInfo

func (m *DirCreateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DirListRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirListRequest) Reset()         { *m = DirListRequest{} }
func (m *DirListRequest) String() string { return proto.CompactTextString(m) }
func (*DirListRequest) ProtoMessage()    {}
func (*DirListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{19}
}

func (m *DirListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirListRequest.Unmarshal(m, b)
}
func (m *DirListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirListRequest.Marshal(b, m, deterministic)
}
func (m *DirListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirListRequest.Merge(m, src)
}
func (m *DirListRequest) XXX_Size() int {
	return xxx_messageInfo_DirListRequest.Size(m)
}
func (m *DirListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DirListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DirListRequest proto.InternalMessageInfo

func (m *DirListRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DirListResponse struct {
	Entries              []*FileEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DirListResponse) Reset()         { *m = DirListResponse{} }
func (m *DirListResponse) String() string { return proto.CompactTextString(m) }
func (*DirListResponse) ProtoMessage()    {}
func (*DirListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{20}
}

func (m *DirListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirListResponse.Unmarshal(m, b)
}
func (m *DirListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirListResponse.Marshal(b, m, deterministic)
}
func (m *DirListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirListResponse.Merge(m, src)
}
func (m *DirListResponse) XXX_Size() int {
	return xxx_messageInfo_DirListResponse.Size(m)
}
func (m *DirListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DirListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DirListResponse proto.InternalMessageInfo

func (m *DirListResponse) GetEntries() []*FileEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type FileEntry struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	IsDir                bool     `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size                 int64    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Mode                 uint32   `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime              int64    `protobuf:"varint,6,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileEntry) Reset()         { *m = FileEntry{} }
func (m *FileEntry) String() string { return proto.CompactTextString(m) }
func (*FileEntry) ProtoMessage()    {}
func (*FileEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{21}
}

func (m *FileEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileEntry.Unmarshal(m, b)
}
func (m *FileEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileEntry.Marshal(b, m, deterministic)
}
func (m *FileEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileEntry.Merge(m, src)
}
func (m *FileEntry) XXX_Size() int {
	return xxx_messageInfo_FileEntry.Size(m)
}
func (m *FileEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FileEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FileEntry proto.InternalMessageInfo

func (m *FileEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FileEntry) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileEntry) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *FileEntry) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FileEntry) GetMode() uint32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *FileEntry) GetModTime() int64 {
	if m != nil {
		return m.ModTime
	}
	return 0
}

type NginxSiteApplyRequest struct {
	Action               NginxSiteAction `protobuf:"varint,1,opt,name=action,proto3,enum=agent.v1.NginxSiteAction" json:"action,omitempty"`
	Domain               string          `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	RootPath             string          `protobuf:"bytes,3,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	PhpVersion           string          `protobuf:"bytes,4,opt,name=php_version,json=phpVersion,proto3" json:"php_version,omitempty"`
	SslEnabled           bool            `protobuf:"varint,5,opt,name=ssl_enabled,json=sslEnabled,proto3" json:"ssl_enabled,omitempty"`
	SslCert              string          `protobuf:"bytes,6,opt,name=ssl_cert,json=sslCert,proto3" json:"ssl_cert,omitempty"`
	SslKey               string          `protobuf:"bytes,7,opt,name=ssl_key,json=sslKey,proto3" json:"ssl_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NginxSiteApplyRequest) Reset()         { *m = NginxSiteApplyRequest{} }
func (m *NginxSiteApplyRequest) String() string { return proto.CompactTextString(m) }
func (*NginxSiteApplyRequest) ProtoMessage()    {}
func (*NginxSiteApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{22}
}

func (m *NginxSiteApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NginxSiteApplyRequest.Unmarshal(m, b)
}
func (m *NginxSiteApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NginxSiteApplyRequest.Marshal(b, m, deterministic)
}
func (m *NginxSiteApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NginxSiteApplyRequest.Merge(m, src)
}
func (m *NginxSiteApplyRequest) XXX_Size() int {
	return xxx_messageInfo_NginxSiteApplyRequest.Size(m)
}
func (m *NginxSiteApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NginxSiteApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NginxSiteApplyRequest proto.InternalMessageInfo

func (m *NginxSiteApplyRequest) GetAction() NginxSiteAction {
	if m != nil {
		return m.Action
	}
	return NginxSiteAction_NGINX_SITE_ACTION_UNSPECIFIED
}

func (m *NginxSiteApplyRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *NginxSiteApplyRequest) GetRootPath() string {
	if m != nil {
		return m.RootPath
	}
	return ""
}

func (m *NginxSiteApplyRequest) GetPhpVersion() string {
	if m != nil {
		return m.PhpVersion
	}
	return ""
}

func (m *NginxSiteApplyRequest) GetSslEnabled() bool {
	if m != nil {
		return m.SslEnabled
	}
	return false
}

func (m *NginxSiteApplyRequest) GetSslCert() string {
	if m != nil {
		return m.SslCert
	}
	return ""
}

func (m *NginxSiteApplyRequest) GetSslKey() string {
	if m != nil {
		return m.SslKey
	}
	return ""
}

type NginxSiteApplyResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NginxSiteApplyResponse) Reset()         { *m = NginxSiteApplyResponse{} }
func (m *NginxSiteApplyResponse) String() string { return proto.CompactTextString(m) }
func (*NginxSiteApplyResponse) ProtoMessage()    {}
func (*NginxSiteApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{23}
}

func (m *NginxSiteApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NginxSiteApplyResponse.Unmarshal(m, b)
}
func (m *NginxSiteApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NginxSiteApplyResponse.Marshal(b, m, deterministic)
}
func (m *NginxSiteApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NginxSiteApplyResponse.Merge(m, src)
}
func (m *NginxSiteApplyResponse) XXX_Size() int {
	return xxx_messageInfo_NginxSiteApplyResponse.Size(m)
}
func (m *NginxSiteApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NginxSiteApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NginxSiteApplyResponse proto.InternalMessageInfo

func (m *NginxSiteApplyResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NginxSiteApplyResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FirewallRuleRequest struct {
	Port                 int32          `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol             string         `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Action               FirewallAction `protobuf:"varint,3,opt,name=action,proto3,enum=agent.v1.FirewallAction" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FirewallRuleRequest) Reset()         { *m = FirewallRuleRequest{} }
func (m *FirewallRuleRequest) String() string { return proto.CompactTextString(m) }
func (*FirewallRuleRequest) ProtoMessage()    {}
func (*FirewallRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{24}
}

func (m *FirewallRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallRuleRequest.Unmarshal(m, b)
}
func (m *FirewallRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallRuleRequest.Marshal(b, m, deterministic)
}
func (m *FirewallRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallRuleRequest.Merge(m, src)
}
func (m *FirewallRuleRequest) XXX_Size() int {
	return xxx_messageInfo_FirewallRuleRequest.Size(m)
}
func (m *FirewallRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallRuleRequest proto.InternalMessageInfo

func (m *FirewallRuleRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *FirewallRuleRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *FirewallRuleRequest) GetAction() FirewallAction {
	if m != nil {
		return m.Action
	}
	return FirewallAction_FIREWALL_ACTION_UNSPECIFIED
}

type FirewallRuleResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirewallRuleResponse) Reset()         { *m = FirewallRuleResponse{} }
func (m *FirewallRuleResponse) String() string { return proto.CompactTextString(m) }
func (*FirewallRuleResponse) ProtoMessage()    {}
func (*FirewallRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{25}
}

func (m *FirewallRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallRuleResponse.Unmarshal(m, b)
}
func (m *FirewallRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallRuleResponse.Marshal(b, m, deterministic)
}
func (m *FirewallRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallRuleResponse.Merge(m, src)
}
func (m *FirewallRuleResponse) XXX_Size() int {
	return xxx_messageInfo_FirewallRuleResponse.Size(m)
}
func (m *FirewallRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallRuleResponse proto.InternalMessageInfo

func (m *FirewallRuleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *FirewallRuleResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FirewallListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirewallListRequest) Reset()         { *m = FirewallListRequest{} }
func (m *FirewallListRequest) String() string { return proto.CompactTextString(m) }
func (*FirewallListRequest) ProtoMessage()    {}
func (*FirewallListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{26}
}

func (m *FirewallListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallListRequest.Unmarshal(m, b)
}
func (m *FirewallListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallListRequest.Marshal(b, m, deterministic)
}
func (m *FirewallListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallListRequest.Merge(m, src)
}
func (m *FirewallListRequest) XXX_Size() int {
	return xxx_messageInfo_FirewallListRequest.Size(m)
}
func (m *FirewallListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallListRequest proto.InternalMessageInfo

type FirewallListResponse struct {
	Rules                []*FirewallEntry `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *FirewallListResponse) Reset()         { *m = FirewallListResponse{} }
func (m *FirewallListResponse) String() string { return proto.CompactTextString(m) }
func (*FirewallListResponse) ProtoMessage()    {}
func (*FirewallListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{27}
}

func (m *FirewallListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallListResponse.Unmarshal(m, b)
}
func (m *FirewallListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallListResponse.Marshal(b, m, deterministic)
}
func (m *FirewallListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallListResponse.Merge(m, src)
}
func (m *FirewallListResponse) XXX_Size() int {
	return xxx_messageInfo_FirewallListResponse.Size(m)
}
func (m *FirewallListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallListResponse proto.InternalMessageInfo

func (m *FirewallListResponse) GetRules() []*FirewallEntry {
	if m != nil {
		return m.Rules
	}
	return nil
}

type FirewallEntry struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Protocol             string   `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirewallEntry) Reset()         { *m = FirewallEntry{} }
func (m *FirewallEntry) String() string { return proto.CompactTextString(m) }
func (*FirewallEntry) ProtoMessage()    {}
func (*FirewallEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{28}
}

func (m *FirewallEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallEntry.Unmarshal(m, b)
}
func (m *FirewallEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallEntry.Marshal(b, m, deterministic)
}
func (m *FirewallEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallEntry.Merge(m, src)
}
func (m *FirewallEntry) XXX_Size() int {
	return xxx_messageInfo_FirewallEntry.Size(m)
}
func (m *FirewallEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallEntry proto.InternalMessageInfo

func (m *FirewallEntry) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *FirewallEntry) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *FirewallEntry) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type SystemStatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemStatsRequest) Reset()         { *m = SystemStatsRequest{} }
func (m *SystemStatsRequest) String() string { return proto.CompactTextString(m) }
func (*SystemStatsRequest) ProtoMessage()    {}
func (*SystemStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{29}
}

func (m *SystemStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStatsRequest.Unmarshal(m, b)
}
func (m *SystemStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStatsRequest.Marshal(b, m, deterministic)
}
func (m *SystemStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStatsRequest.Merge(m, src)
}
func (m *SystemStatsRequest) XXX_Size() int {
	return xxx_messageInfo_SystemStatsRequest.Size(m)
}
func (m *SystemStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStatsRequest proto.InternalMessageInfo

type SystemStatsResponse struct {
	CpuUsagePercent      float64          `protobuf:"fixed64,1,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	CpuCores             int32            `protobuf:"varint,2,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryTotal          uint64           `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed           uint64           `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryFree           uint64           `protobuf:"varint,5,opt,name=memory_free,json=memoryFree,proto3" json:"memory_free,omitempty"`
	SwapTotal            uint64           `protobuf:"varint,6,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed             uint64           `protobuf:"varint,7,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	Disk                 []*DiskStatEntry `protobuf:"bytes,8,rep,name=disk,proto3" json:"disk,omitempty"`
	NetBytesSent         uint64           `protobuf:"varint,9,opt,name=net_bytes_sent,json=netBytesSent,proto3" json:"net_bytes_sent,omitempty"`
	NetBytesRecv         uint64           `protobuf:"varint,10,opt,name=net_bytes_recv,json=netBytesRecv,proto3" json:"net_bytes_recv,omitempty"`
	Load_1               float64          `protobuf:"fixed64,11,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5               float64          `protobuf:"fixed64,12,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15              float64          `protobuf:"fixed64,13,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	Temperature          float64          `protobuf:"fixed64,14,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Uptime               int64            `protobuf:"varint,15,opt,name=uptime,proto3" json:"uptime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SystemStatsResponse) Reset()         { *m = SystemStatsResponse{} }
func (m *SystemStatsResponse) String() string { return proto.CompactTextString(m) }
func (*SystemStatsResponse) ProtoMessage()    {}
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{30}
}

func (m *SystemStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStatsResponse.Unmarshal(m, b)
}
func (m *SystemStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStatsResponse.Marshal(b, m, deterministic)
}
func (m *SystemStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStatsResponse.Merge(m, src)
}
func (m *SystemStatsResponse) XXX_Size() int {
	return xxx_messageInfo_SystemStatsResponse.Size(m)
}
func (m *SystemStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStatsResponse proto.InternalMessageInfo

func (m *SystemStatsResponse) GetCpuUsagePercent() float64 {
	if m != nil {
		return m.CpuUsagePercent
	}
	return 0
}

func (m *SystemStatsResponse) GetCpuCores() int32 {
	if m != nil {
		return m.CpuCores
	}
	return 0
}

func (m *SystemStatsResponse) GetMemoryTotal() uint64 {
	if m != nil {
		return m.MemoryTotal
	}
	return 0
}

func (m *SystemStatsResponse) GetMemoryUsed() uint64 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *SystemStatsResponse) GetMemoryFree() uint64 {
	if m != nil {
		return m.MemoryFree
	}
	return 0
}

func (m *SystemStatsResponse) GetSwapTotal() uint64 {
	if m != nil {
		return m.SwapTotal
	}
	return 0
}

func (m *SystemStatsResponse) GetSwapUsed() uint64 {
	if m != nil {
		return m.SwapUsed
	}
	return 0
}

func (m *SystemStatsResponse) GetDisk() []*DiskStatEntry {
	if m != nil {
		return m.Disk
	}
	return nil
}

func (m *SystemStatsResponse) GetNetBytesSent() uint64 {
	if m != nil {
		return m.NetBytesSent
	}
	return 0
}

func (m *SystemStatsResponse) GetNetBytesRecv() uint64 {
	if m != nil {
		return m.NetBytesRecv
	}
	return 0
}

func (m *SystemStatsResponse) GetLoad_1() float64 {
	if m != nil {
		return m.Load_1
	}
	return 0
}

func (m *SystemStatsResponse) GetLoad_5() float64 {
	if m != nil {
		return m.Load_5
	}
	return 0
}

func (m *SystemStatsResponse) GetLoad_15() float64 {
	if m != nil {
		return m.Load_15
	}
	return 0
}

func (m *SystemStatsResponse) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *SystemStatsResponse) GetUptime() int64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

type DiskStatEntry struct {
	Mountpoint           string   `protobuf:"bytes,1,opt,name=mountpoint,proto3" json:"mountpoint,omitempty"`
	Total                uint64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Used                 uint64   `protobuf:"varint,3,opt,name=used,proto3" json:"used,omitempty"`
	Free                 uint64   `protobuf:"varint,4,opt,name=free,proto3" json:"free,omitempty"`
	UsedPercent          float64  `protobuf:"fixed64,5,opt,name=used_percent,json=usedPercent,proto3" json:"used_percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskStatEntry) Reset()         { *m = DiskStatEntry{} }
func (m *DiskStatEntry) String() string { return proto.CompactTextString(m) }
func (*DiskStatEntry) ProtoMessage()    {}
func (*DiskStatEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{31}
}

func (m *DiskStatEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskStatEntry.Unmarshal(m, b)
}
func (m *DiskStatEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskStatEntry.Marshal(b, m, deterministic)
}
func (m *DiskStatEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskStatEntry.Merge(m, src)
}
func (m *DiskStatEntry) XXX_Size() int {
	return xxx_messageInfo_DiskStatEntry.Size(m)
}
func (m *DiskStatEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskStatEntry.DiscardUnknown(m)
}

var xxx_messageInfo_DiskStatEntry proto.InternalMessageInfo

func (m *DiskStatEntry) GetMountpoint() string {
	if m != nil {
		return m.Mountpoint
	}
	return ""
}

func (m *DiskStatEntry) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DiskStatEntry) GetUsed() uint64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func (m *DiskStatEntry) GetFree() uint64 {
	if m != nil {
		return m.Free
	}
	return 0
}

func (m *DiskStatEntry) GetUsedPercent() float64 {
	if m != nil {
		return m.UsedPercent
	}
	return 0
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{32}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6d5894091b396a9, []int{33}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterEnum("agent.v1.ServiceActionType", ServiceActionType_name, ServiceActionType_value)
	proto.RegisterEnum("agent.v1.NginxSiteAction", NginxSiteAction_name, NginxSiteAction_value)
	proto.RegisterEnum("agent.v1.FirewallAction", FirewallAction_name, FirewallAction_value)
	proto.RegisterType((*ServiceActionRequest)(nil), "agent.v1.ServiceActionRequest")
	proto.RegisterType((*ServiceActionResponse)(nil), "agent.v1.ServiceActionResponse")
	proto.RegisterType((*ServiceStatusRequest)(nil), "agent.v1.ServiceStatusRequest")
	proto.RegisterType((*ServiceStatusResponse)(nil), "agent.v1.ServiceStatusResponse")
	proto.RegisterType((*ServiceLogsRequest)(nil), "agent.v1.ServiceLogsRequest")
	proto.RegisterType((*LogLine)(nil), "agent.v1.LogLine")
	proto.RegisterType((*CommandExecuteRequest)(nil), "agent.v1.CommandExecuteRequest")
	proto.RegisterType((*CommandExecuteResponse)(nil), "agent.v1.CommandExecuteResponse")
	proto.RegisterType((*PackageRequest)(nil), "agent.v1.PackageRequest")
	proto.RegisterType((*PackageOutput)(nil), "agent.v1.PackageOutput")
	proto.RegisterType((*PackageStatusResponse)(nil), "agent.v1.PackageStatusResponse")
	proto.RegisterType((*FileReadRequest)(nil), "agent.v1.FileReadRequest")
	proto.RegisterType((*FileReadResponse)(nil), "agent.v1.FileReadResponse")
	proto.RegisterType((*FileWriteRequest)(nil), "agent.v1.FileWriteRequest")
	proto.RegisterType((*FileWriteResponse)(nil), "agent.v1.FileWriteResponse")
	proto.RegisterType((*FileDeleteRequest)(nil), "agent.v1.FileDeleteRequest")
	proto.RegisterType((*FileDeleteResponse)(nil), "agent.v1.FileDeleteResponse")
	proto.RegisterType((*DirCreateRequest)(nil), "agent.v1.DirCreateRequest")
	proto.RegisterType((*DirCreateResponse)(nil), "agent.v1.DirCreateResponse")
	proto.RegisterType((*DirListRequest)(nil), "agent.v1.DirListRequest")
	proto.RegisterType((*DirListResponse)(nil), "agent.v1.DirListResponse")
	proto.RegisterType((*FileEntry)(nil), "agent.v1.FileEntry")
	proto.RegisterType((*NginxSiteApplyRequest)(nil), "agent.v1.NginxSiteApplyRequest")
	proto.RegisterType((*NginxSiteApplyResponse)(nil), "agent.v1.NginxSiteApplyResponse")
	proto.RegisterType((*FirewallRuleRequest)(nil), "agent.v1.FirewallRuleRequest")
	proto.RegisterType((*FirewallRuleResponse)(nil), "agent.v1.FirewallRuleResponse")
	proto.RegisterType((*FirewallListRequest)(nil), "agent.v1.FirewallListRequest")
	proto.RegisterType((*FirewallListResponse)(nil), "agent.v1.FirewallListResponse")
	proto.RegisterType((*FirewallEntry)(nil), "agent.v1.FirewallEntry")
	proto.RegisterType((*SystemStatsRequest)(nil), "agent.v1.SystemStatsRequest")
	proto.RegisterType((*SystemStatsResponse)(nil), "agent.v1.SystemStatsResponse")
	proto.RegisterType((*DiskStatEntry)(nil), "agent.v1.DiskStatEntry")
	proto.RegisterType((*PingRequest)(nil), "agent.v1.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "agent.v1.PingResponse")
}

func init() {
	proto.RegisterFile("proto/agent/v1/agent.proto", fileDescriptor_d6d5894091b396a9)
}

var fileDescriptor_d6d5894091b396a9 = []byte{
	// 1772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x4b, 0x73, 0xdb, 0xc8,
	0x11, 0x0e, 0x45, 0x52, 0x22, 0x9b, 0x7a, 0xd0, 0x63, 0x51, 0xa6, 0xa8, 0x87, 0xbd, 0xa8, 0x4d,
	0xc5, 0xe5, 0x64, 0x25, 0xcb, 0x2e, 0x1d, 0xb2, 0x5b, 0x95, 0x5a, 0x5a, 0x84, 0xb6, 0xe8, 0xe5,
	0x4a, 0x2a, 0x90, 0x5e, 0x27, 0xb9, 0xa0, 0x20, 0x60, 0x42, 0xa3, 0x84, 0x57, 0x66, 0x06, 0xb2,
	0x99, 0x63, 0xee, 0xa9, 0xca, 0x0f, 0xc8, 0x5f, 0xc8, 0x35, 0xbf, 0x24, 0x7f, 0x25, 0x87, 0xdc,
	0x52, 0xf3, 0xc0, 0x93, 0xa0, 0x9d, 0x5d, 0xdf, 0xa6, 0xbf, 0xee, 0xe9, 0xe9, 0xee, 0xe9, 0x69,
	0x74, 0x03, 0x06, 0x11, 0x09, 0x59, 0x78, 0x6a, 0xcd, 0x71, 0xc0, 0x4e, 0xef, 0xcf, 0xe4, 0xe2,
	0x44, 0x80, 0xa8, 0x25, 0x89, 0xfb, 0x33, 0x2d, 0x80, 0xdd, 0x29, 0x26, 0xf7, 0xae, 0x8d, 0x87,
	0x36, 0x73, 0xc3, 0xc0, 0xc0, 0x7f, 0x8e, 0x31, 0x65, 0xe8, 0x0b, 0xd8, 0xa4, 0x12, 0x37, 0x03,
	0xcb, 0xc7, 0xfd, 0xda, 0x93, 0xda, 0xd3, 0xb6, 0xd1, 0x51, 0xd8, 0x95, 0xe5, 0x63, 0xf4, 0x12,
	0xd6, 0x2d, 0xb1, 0xa7, 0xbf, 0xf6, 0xa4, 0xf6, 0x74, 0xfb, 0xc5, 0xc1, 0x49, 0xa2, 0xf5, 0xa4,
	0xa0, 0x72, 0xb6, 0x88, 0xb0, 0xa1, 0x44, 0xb5, 0xef, 0xa1, 0x57, 0x3a, 0x8f, 0x46, 0x61, 0x40,
	0x31, 0xea, 0xc3, 0x06, 0x8d, 0x6d, 0x1b, 0x53, 0x2a, 0xce, 0x6a, 0x19, 0x09, 0xc9, 0x39, 0x3e,
	0xa6, 0xd4, 0x9a, 0x63, 0x71, 0x50, 0xdb, 0x48, 0x48, 0xed, 0xb7, 0xa9, 0xf1, 0x53, 0x66, 0xb1,
	0x98, 0xfe, 0xff, 0xc6, 0x6b, 0xff, 0xa8, 0xa5, 0x86, 0x24, 0x7b, 0x95, 0x21, 0x08, 0x1a, 0xb9,
	0x4d, 0x62, 0x8d, 0xf6, 0xa4, 0xab, 0xf7, 0xd2, 0x82, 0x96, 0xa1, 0x28, 0x6e, 0x1a, 0x0e, 0xac,
	0x5b, 0x0f, 0x3b, 0xfd, 0xba, 0x34, 0x5a, 0x91, 0xe8, 0x00, 0xda, 0x34, 0xbe, 0x35, 0x29, 0xb3,
	0x18, 0xee, 0x37, 0x84, 0xaa, 0x16, 0x8d, 0x6f, 0xf9, 0x59, 0x18, 0x3d, 0x81, 0x8e, 0x83, 0xa9,
	0x4d, 0xdc, 0x48, 0x84, 0xaf, 0x29, 0xcd, 0xcb, 0x41, 0xda, 0x0f, 0x80, 0x94, 0x75, 0x93, 0x70,
	0xfe, 0x13, 0xfc, 0x42, 0xbb, 0xd0, 0xf4, 0xdc, 0x00, 0x53, 0x61, 0x68, 0xd3, 0x90, 0x84, 0xf6,
	0x0d, 0x6c, 0x4c, 0xc2, 0xf9, 0xc4, 0x0d, 0x84, 0x7b, 0x1c, 0x4b, 0xdc, 0xe3, 0x6b, 0x74, 0x08,
	0x6d, 0xe6, 0xfa, 0x98, 0x32, 0xcb, 0x8f, 0xc4, 0xc6, 0xba, 0x91, 0x01, 0x9a, 0x0e, 0xbd, 0x8b,
	0xd0, 0xf7, 0xad, 0xc0, 0xd1, 0x3f, 0x60, 0x3b, 0x66, 0x38, 0x31, 0xa7, 0x0f, 0x1b, 0xb6, 0x64,
	0x28, 0x6d, 0x09, 0xc9, 0x0f, 0xb1, 0xc8, 0x9c, 0x1b, 0x51, 0xe7, 0x87, 0xf0, 0xb5, 0x86, 0x61,
	0xaf, 0xac, 0x46, 0x45, 0xfc, 0x00, 0xda, 0xf8, 0x83, 0xcb, 0x4c, 0x3b, 0x74, 0xa4, 0x5d, 0x4d,
	0xa3, 0xc5, 0x81, 0x8b, 0xd0, 0x11, 0xa1, 0xa7, 0xcc, 0x09, 0x63, 0xa6, 0x2e, 0x5f, 0x51, 0x0a,
	0xc7, 0x84, 0x88, 0xc8, 0x4b, 0x1c, 0x13, 0xa2, 0xbd, 0x84, 0xed, 0x1b, 0xcb, 0xbe, 0xb3, 0xe6,
	0x38, 0x17, 0xb5, 0x48, 0x22, 0x85, 0xa8, 0x29, 0x4c, 0x64, 0xc3, 0xd7, 0xb0, 0xa5, 0x36, 0x5d,
	0xc7, 0x2c, 0x8a, 0x59, 0x65, 0x94, 0x7a, 0xb0, 0xee, 0x52, 0x93, 0x9f, 0x28, 0x93, 0xa0, 0xe9,
	0x52, 0x9d, 0x10, 0xed, 0x1a, 0x7a, 0x6a, 0x6f, 0x29, 0x91, 0x0e, 0xa1, 0xed, 0x06, 0x94, 0x59,
	0x1e, 0x4f, 0x0f, 0x99, 0xd3, 0x19, 0xc0, 0x83, 0x77, 0x8f, 0x09, 0x4d, 0x9e, 0x4f, 0xdb, 0x48,
	0x48, 0xed, 0x97, 0xb0, 0x73, 0xe9, 0x7a, 0xd8, 0xc0, 0x96, 0x93, 0xb8, 0x80, 0xa0, 0x11, 0x59,
	0xec, 0x5d, 0x62, 0x0e, 0x5f, 0x6b, 0xbf, 0x81, 0x6e, 0x26, 0x96, 0x3d, 0x22, 0x3b, 0x0c, 0x18,
	0x0e, 0x98, 0x10, 0xdd, 0x34, 0x12, 0x52, 0x9b, 0x49, 0xe9, 0xb7, 0xc4, 0xcd, 0xee, 0xaf, 0x42,
	0x6b, 0x5e, 0xc3, 0x5a, 0x41, 0x03, 0x97, 0xf6, 0xf9, 0x05, 0xf1, 0x70, 0x6f, 0x19, 0x62, 0xad,
	0x7d, 0x05, 0x0f, 0x72, 0x5a, 0x3f, 0xf5, 0x92, 0xb5, 0x5f, 0x49, 0xf1, 0x11, 0xf6, 0xf0, 0x47,
	0xad, 0xd0, 0x4e, 0x00, 0xe5, 0x05, 0x3f, 0xa9, 0xf8, 0x6b, 0xe8, 0x8e, 0x5c, 0x72, 0x41, 0xb0,
	0xf5, 0x71, 0xef, 0x12, 0x1f, 0xd6, 0x8a, 0x3e, 0xe4, 0xf6, 0x7e, 0xf2, 0xa8, 0x2f, 0x61, 0x7b,
	0xe4, 0x92, 0x89, 0x4b, 0xd9, 0xc7, 0x1c, 0xf8, 0x16, 0x76, 0x52, 0x29, 0xa5, 0xf2, 0x2b, 0x5e,
	0x2b, 0x18, 0x71, 0x31, 0x57, 0x59, 0x7f, 0xda, 0x79, 0xf1, 0x30, 0xab, 0x97, 0xdc, 0x59, 0x3d,
	0x60, 0x64, 0x61, 0x24, 0x32, 0xda, 0xdf, 0x6a, 0xd0, 0x4e, 0xe1, 0xca, 0xa2, 0x94, 0x9c, 0xbb,
	0x96, 0x73, 0x50, 0xe6, 0xa8, 0xe3, 0x12, 0x55, 0x8f, 0x9a, 0x2e, 0x1d, 0xb9, 0x84, 0x8b, 0x52,
	0xf7, 0x2f, 0xb2, 0x10, 0xd5, 0x0d, 0xb1, 0x4e, 0x63, 0xd1, 0xcc, 0x62, 0x81, 0xf6, 0xa1, 0xe5,
	0x87, 0x8e, 0xc9, 0xdf, 0x7e, 0x7f, 0x5d, 0xc8, 0x6e, 0xf8, 0xa1, 0x33, 0x73, 0x7d, 0xac, 0xfd,
	0xa7, 0x06, 0xbd, 0xab, 0xb9, 0x1b, 0x7c, 0x98, 0xba, 0x0c, 0x0f, 0xa3, 0xc8, 0x5b, 0x24, 0xfe,
	0x9f, 0xa5, 0xdf, 0x81, 0x9a, 0xf8, 0x0e, 0xec, 0x67, 0x7e, 0x65, 0x1b, 0x64, 0xb1, 0x57, 0x82,
	0xfc, 0xf1, 0x3a, 0xa1, 0x6f, 0xb9, 0x49, 0xee, 0x2b, 0x8a, 0x57, 0x02, 0x12, 0x86, 0xcc, 0x14,
	0x7e, 0xc9, 0x77, 0xdd, 0xe2, 0xc0, 0x0d, 0xf7, 0xed, 0x31, 0x74, 0xa2, 0x77, 0x91, 0x99, 0xbc,
	0x1a, 0x59, 0x54, 0x21, 0x7a, 0x17, 0xfd, 0x28, 0x11, 0x2e, 0x40, 0xa9, 0x67, 0x26, 0x15, 0xb9,
	0x29, 0x22, 0x00, 0x94, 0x7a, 0xba, 0x2a, 0xca, 0xfb, 0xd0, 0xe2, 0x02, 0x36, 0x26, 0x4c, 0xb8,
	0xd7, 0x36, 0x36, 0x28, 0xf5, 0x2e, 0x30, 0x61, 0xe8, 0x11, 0xf0, 0xa5, 0x79, 0x87, 0x17, 0xfd,
	0x0d, 0x55, 0x4f, 0xa8, 0xf7, 0x3d, 0x5e, 0x68, 0x13, 0xd8, 0x2b, 0xbb, 0xfd, 0x19, 0x5f, 0xac,
	0xf7, 0xf0, 0xf0, 0xd2, 0x25, 0xf8, 0xbd, 0xe5, 0x79, 0x46, 0xec, 0x15, 0x72, 0x35, 0x24, 0x4c,
	0x15, 0x3f, 0xb1, 0x46, 0x03, 0x68, 0x89, 0x8f, 0xb5, 0x1d, 0x7a, 0x4a, 0x4b, 0x4a, 0xa3, 0xe7,
	0x69, 0xc8, 0xeb, 0x22, 0xe4, 0xfd, 0x7c, 0x2a, 0x49, 0xf5, 0xc5, 0x88, 0x6b, 0xaf, 0x61, 0xb7,
	0x78, 0xf0, 0x67, 0x38, 0xd1, 0xcb, 0x9c, 0xc8, 0xbd, 0x03, 0x4d, 0xcf, 0x8e, 0x28, 0x25, 0x7e,
	0x93, 0xc4, 0x5e, 0x9a, 0xf6, 0x8f, 0x96, 0x6d, 0x95, 0xa9, 0x2f, 0xa5, 0xb4, 0xb7, 0xb0, 0x55,
	0xc0, 0x7f, 0x72, 0x70, 0xf6, 0x0a, 0xc1, 0x69, 0xa7, 0x21, 0xd8, 0x05, 0x34, 0x5d, 0x50, 0x86,
	0x7d, 0x5e, 0xa7, 0x93, 0x6f, 0xaa, 0xf6, 0xdf, 0x3a, 0x3c, 0x2c, 0xc0, 0xca, 0xea, 0x67, 0xf0,
	0xc0, 0x8e, 0x62, 0x33, 0xe6, 0x1e, 0x9b, 0x11, 0x26, 0x76, 0x52, 0x54, 0x6b, 0xc6, 0x8e, 0x1d,
	0xc5, 0x6f, 0x38, 0x7e, 0x23, 0x61, 0x9e, 0xb6, 0x5c, 0xd6, 0x0e, 0x49, 0xfa, 0xe1, 0x6d, 0xd9,
	0x51, 0x7c, 0xc1, 0x69, 0xfe, 0xf9, 0xf1, 0xb1, 0x1f, 0x92, 0x85, 0xc9, 0x42, 0x66, 0x79, 0xc2,
	0xa8, 0x86, 0xd1, 0x91, 0xd8, 0x8c, 0x43, 0x3c, 0x71, 0x95, 0x48, 0x4c, 0xb1, 0x23, 0x32, 0xbb,
	0x61, 0x80, 0x84, 0xde, 0x50, 0xec, 0xe4, 0x04, 0xfe, 0x44, 0xb0, 0x7c, 0xb2, 0xa9, 0xc0, 0x25,
	0xc1, 0x18, 0x1d, 0x01, 0xd0, 0xf7, 0x56, 0xa4, 0x8e, 0x58, 0x17, 0xfc, 0x36, 0x47, 0xe4, 0x01,
	0xbc, 0x1b, 0xe1, 0x6c, 0xa1, 0x7e, 0x43, 0x70, 0x5b, 0x1c, 0x10, 0xca, 0x7f, 0x0d, 0x0d, 0xc7,
	0xa5, 0x77, 0xfd, 0x56, 0xf9, 0x7a, 0x46, 0x2e, 0xbd, 0xe3, 0x41, 0x91, 0xd7, 0x23, 0x84, 0xd0,
	0x97, 0xb0, 0x1d, 0x60, 0x66, 0xde, 0x2e, 0x18, 0xa6, 0x26, 0xe5, 0x31, 0x69, 0x0b, 0x75, 0x9b,
	0x01, 0x66, 0xaf, 0x38, 0x38, 0xe5, 0x01, 0x29, 0x48, 0x11, 0x6c, 0xdf, 0xf7, 0xa1, 0x28, 0x65,
	0x60, 0xfb, 0x9e, 0x17, 0x2b, 0x2f, 0xb4, 0x1c, 0xf3, 0xac, 0xdf, 0x11, 0x71, 0x6d, 0x72, 0xea,
	0x2c, 0x85, 0xcf, 0xfb, 0x9b, 0x19, 0x7c, 0xce, 0x5f, 0xa8, 0x94, 0x3e, 0xef, 0x6f, 0x09, 0x5c,
	0x48, 0x9d, 0x9d, 0xf3, 0x6e, 0x8a, 0x61, 0x3f, 0xc2, 0xc4, 0x62, 0x31, 0xc1, 0xfd, 0x6d, 0xc1,
	0xcc, 0x43, 0x3c, 0x23, 0xe2, 0x48, 0x14, 0xb5, 0x1d, 0x51, 0xd4, 0x14, 0xa5, 0xfd, 0xbd, 0x06,
	0x5b, 0x05, 0x27, 0xd1, 0x31, 0x80, 0x1f, 0xc6, 0x01, 0x8b, 0x42, 0x57, 0x5d, 0x77, 0xdb, 0xc8,
	0x21, 0xbc, 0xbd, 0x92, 0x21, 0x5e, 0x13, 0xfe, 0x48, 0x82, 0x67, 0xa8, 0x88, 0xac, 0xbc, 0x5a,
	0xb1, 0xe6, 0x98, 0xb8, 0x2b, 0x79, 0x99, 0x62, 0xcd, 0x53, 0x81, 0xf3, 0xd2, 0x74, 0x6a, 0x4a,
	0x53, 0x39, 0xa6, 0x52, 0x49, 0xdb, 0x82, 0xce, 0x8d, 0x1b, 0xcc, 0x93, 0xec, 0x7c, 0x0a, 0x9b,
	0x92, 0xcc, 0x9e, 0x6b, 0x52, 0xff, 0x6a, 0x85, 0xae, 0xe1, 0xd9, 0xbf, 0x6b, 0xf0, 0x60, 0xa9,
	0xed, 0x46, 0xc7, 0x30, 0x98, 0xea, 0xc6, 0x8f, 0xe3, 0x0b, 0xdd, 0x1c, 0x5e, 0xcc, 0xc6, 0xd7,
	0x57, 0xe6, 0x9b, 0xab, 0xe9, 0x8d, 0x7e, 0x31, 0xbe, 0x1c, 0xeb, 0xa3, 0xee, 0x2f, 0x50, 0x1f,
	0x76, 0x4b, 0xfc, 0xe9, 0x6c, 0x68, 0xcc, 0xba, 0x35, 0xf4, 0x08, 0x1e, 0x2e, 0x71, 0xae, 0x6f,
	0xba, 0x6b, 0x68, 0x00, 0x7b, 0x25, 0x86, 0xa1, 0xcb, 0x4d, 0x75, 0xb4, 0x0f, 0xbd, 0x12, 0x4f,
	0xbf, 0x1a, 0xbe, 0x9a, 0xe8, 0xdd, 0x46, 0xc5, 0xb6, 0xd1, 0x78, 0x2a, 0x78, 0xcd, 0x8a, 0x6d,
	0x86, 0x3e, 0xb9, 0x1e, 0x8e, 0xba, 0xeb, 0xcf, 0xfe, 0x59, 0x83, 0x9d, 0xd2, 0x57, 0x04, 0x7d,
	0x01, 0x47, 0x57, 0xdf, 0x8d, 0xaf, 0x7e, 0x6f, 0x4e, 0xc7, 0xb3, 0x15, 0x7e, 0x1d, 0x42, 0xbf,
	0x42, 0xe4, 0x66, 0xaa, 0x0b, 0xdf, 0x2a, 0xb9, 0x23, 0x7d, 0xa2, 0xcf, 0xf4, 0xee, 0x5a, 0x35,
	0x57, 0xf9, 0x51, 0x47, 0x47, 0xb0, 0x5f, 0xb1, 0x57, 0xb9, 0xd2, 0x78, 0xf6, 0xd7, 0x1a, 0x6c,
	0x17, 0x4b, 0x30, 0x7a, 0x0c, 0x07, 0x97, 0x63, 0x43, 0x7f, 0x3b, 0x9c, 0x4c, 0xaa, 0x8d, 0xdd,
	0x87, 0x5e, 0x59, 0x60, 0x38, 0x99, 0x5c, 0xbf, 0xed, 0xd6, 0xf8, 0xfd, 0x94, 0x59, 0x23, 0xfd,
	0xea, 0x0f, 0xf2, 0x1a, 0x96, 0x39, 0xc2, 0x83, 0xfa, 0x8b, 0x7f, 0x01, 0x6c, 0x0e, 0xf9, 0x2b,
	0x56, 0x09, 0x81, 0x6e, 0x60, 0xab, 0x90, 0x1b, 0xe8, 0x78, 0xc5, 0xac, 0xa6, 0xf2, 0x6e, 0xf0,
	0x78, 0x25, 0x5f, 0x25, 0x62, 0xa6, 0x51, 0x76, 0xbd, 0x15, 0x1a, 0x0b, 0x33, 0x59, 0x85, 0xc6,
	0x52, 0xbb, 0xfc, 0x2d, 0x74, 0x72, 0x23, 0x0f, 0x3a, 0x5c, 0x92, 0xcf, 0x4d, 0x42, 0x83, 0x07,
	0x19, 0x57, 0x0d, 0x36, 0xcf, 0x6b, 0x68, 0x0a, 0xdb, 0xc5, 0x09, 0x03, 0xe5, 0x0e, 0xad, 0x1c,
	0x61, 0x06, 0x4f, 0x56, 0x0b, 0x28, 0xb3, 0xf4, 0x74, 0x9e, 0x18, 0xcb, 0xde, 0x1d, 0xe5, 0x3e,
	0xb6, 0xc5, 0x49, 0x63, 0xf0, 0x68, 0x89, 0x23, 0xc7, 0x89, 0xe7, 0x35, 0x34, 0x4a, 0x27, 0x0c,
	0x03, 0xfb, 0x21, 0x1f, 0x1d, 0x3f, 0x4f, 0xcb, 0x9b, 0xc8, 0xe1, 0x93, 0xe4, 0xcf, 0xd2, 0xf2,
	0x3a, 0xd5, 0xa2, 0xee, 0x6e, 0xb5, 0x96, 0xc7, 0x4b, 0x9c, 0xd2, 0xad, 0x0d, 0xa1, 0x95, 0x4c,
	0x21, 0x68, 0xbf, 0xd8, 0xd0, 0xe6, 0x06, 0x98, 0xc1, 0xa0, 0x8a, 0xa5, 0x54, 0x8c, 0x64, 0xa3,
	0x2b, 0x86, 0x08, 0x54, 0x12, 0xcc, 0xcf, 0x2b, 0x83, 0x83, 0x4a, 0x9e, 0xd2, 0xf2, 0x1d, 0x40,
	0x36, 0x32, 0xa0, 0x92, 0x68, 0x61, 0xe2, 0x18, 0x1c, 0x56, 0x33, 0x33, 0x73, 0xd2, 0x79, 0x20,
	0x6f, 0x4e, 0x79, 0xc0, 0xc8, 0x9b, 0xb3, 0x3c, 0x40, 0xfc, 0x0e, 0x36, 0xd4, 0x00, 0x90, 0x8f,
	0x6e, 0x71, 0x72, 0x18, 0xec, 0x57, 0x70, 0xd4, 0xfe, 0x29, 0x6c, 0x17, 0xdb, 0xce, 0x7c, 0x2e,
	0x57, 0xf6, 0xe1, 0xf9, 0x5c, 0x5e, 0xd1, 0xb1, 0xfe, 0x00, 0x9b, 0xf9, 0x26, 0x10, 0x1d, 0x2d,
	0xb7, 0x62, 0xb9, 0xae, 0x74, 0x70, 0xbc, 0x8a, 0xbd, 0xac, 0x4e, 0x38, 0x5a, 0xa1, 0x2e, 0xef,
	0xed, 0xf1, 0x2a, 0xb6, 0x52, 0xf7, 0x1a, 0x3a, 0xb9, 0x46, 0xac, 0x50, 0x00, 0x96, 0xda, 0xb6,
	0xc1, 0xd1, 0x0a, 0xae, 0xd2, 0x75, 0x0e, 0x0d, 0xfe, 0xdd, 0x44, 0xbd, 0x5c, 0xfe, 0x66, 0x9f,
	0xd5, 0xc1, 0x5e, 0x19, 0x96, 0xdb, 0x5e, 0x9d, 0xff, 0xf1, 0xe5, 0xdc, 0x65, 0xef, 0xe2, 0xdb,
	0x13, 0x3b, 0xf4, 0x4f, 0xad, 0x80, 0x30, 0xec, 0x9c, 0x86, 0x11, 0x0e, 0x1c, 0x1c, 0x79, 0xe1,
	0xe2, 0xb4, 0xf8, 0x4b, 0xed, 0x1b, 0xb1, 0xb8, 0x3f, 0xbb, 0x5d, 0x17, 0xf8, 0xcb, 0xff, 0x05,
	0x00, 0x00, 0xff, 0xff, 0x29, 0xc2, 0x9b, 0x13, 0x73, 0x13, 0x00, 0x00,
}
