// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ServiceAction_FullMethodName     = "/agent.v1.AgentService/ServiceAction"
	AgentService_ServiceStatus_FullMethodName     = "/agent.v1.AgentService/ServiceStatus"
	AgentService_ServiceLogs_FullMethodName       = "/agent.v1.AgentService/ServiceLogs"
	AgentService_ServiceStreamLogs_FullMethodName = "/agent.v1.AgentService/ServiceStreamLogs"
	AgentService_FileLogs_FullMethodName          = "/agent.v1.AgentService/FileLogs"
	AgentService_StreamLogs_FullMethodName        = "/agent.v1.AgentService/StreamLogs"
	AgentService_CommandExecute_FullMethodName    = "/agent.v1.AgentService/CommandExecute"
	AgentService_PackageInstall_FullMethodName    = "/agent.v1.AgentService/PackageInstall"
	AgentService_PackageRemove_FullMethodName     = "/agent.v1.AgentService/PackageRemove"
	AgentService_PackageUpdate_FullMethodName     = "/agent.v1.AgentService/PackageUpdate"
	AgentService_PackageStatus_FullMethodName     = "/agent.v1.AgentService/PackageStatus"
	AgentService_FileRead_FullMethodName          = "/agent.v1.AgentService/FileRead"
	AgentService_FileWrite_FullMethodName         = "/agent.v1.AgentService/FileWrite"
	AgentService_FileDelete_FullMethodName        = "/agent.v1.AgentService/FileDelete"
	AgentService_DirCreate_FullMethodName         = "/agent.v1.AgentService/DirCreate"
	AgentService_DirList_FullMethodName           = "/agent.v1.AgentService/DirList"
	AgentService_FileRename_FullMethodName        = "/agent.v1.AgentService/FileRename"
	AgentService_FileCopy_FullMethodName          = "/agent.v1.AgentService/FileCopy"
	AgentService_FileChmod_FullMethodName         = "/agent.v1.AgentService/FileChmod"
	AgentService_FileChown_FullMethodName         = "/agent.v1.AgentService/FileChown"
	AgentService_ArchiveCreate_FullMethodName     = "/agent.v1.AgentService/ArchiveCreate"
	AgentService_ArchiveExtract_FullMethodName    = "/agent.v1.AgentService/ArchiveExtract"
	AgentService_FileUploadStream_FullMethodName  = "/agent.v1.AgentService/FileUploadStream"
	AgentService_NginxSiteApply_FullMethodName    = "/agent.v1.AgentService/NginxSiteApply"
	AgentService_FirewallRule_FullMethodName      = "/agent.v1.AgentService/FirewallRule"
	AgentService_FirewallDelete_FullMethodName    = "/agent.v1.AgentService/FirewallDelete"
	AgentService_FirewallList_FullMethodName      = "/agent.v1.AgentService/FirewallList"
	AgentService_FirewallStatus_FullMethodName    = "/agent.v1.AgentService/FirewallStatus"
	AgentService_FirewallToggle_FullMethodName    = "/agent.v1.AgentService/FirewallToggle"
	AgentService_FirewallReset_FullMethodName     = "/agent.v1.AgentService/FirewallReset"
	AgentService_CronList_FullMethodName          = "/agent.v1.AgentService/CronList"
	AgentService_CronGet_FullMethodName           = "/agent.v1.AgentService/CronGet"
	AgentService_CronCreate_FullMethodName        = "/agent.v1.AgentService/CronCreate"
	AgentService_CronUpdate_FullMethodName        = "/agent.v1.AgentService/CronUpdate"
	AgentService_CronDelete_FullMethodName        = "/agent.v1.AgentService/CronDelete"
	AgentService_CronEnable_FullMethodName        = "/agent.v1.AgentService/CronEnable"
	AgentService_CronDisable_FullMethodName       = "/agent.v1.AgentService/CronDisable"
	AgentService_CronRun_FullMethodName           = "/agent.v1.AgentService/CronRun"
	AgentService_CronHistory_FullMethodName       = "/agent.v1.AgentService/CronHistory"
	AgentService_CronLogs_FullMethodName          = "/agent.v1.AgentService/CronLogs"
	AgentService_CronImport_FullMethodName        = "/agent.v1.AgentService/CronImport"
	AgentService_CronExport_FullMethodName        = "/agent.v1.AgentService/CronExport"
	AgentService_CronValidate_FullMethodName      = "/agent.v1.AgentService/CronValidate"
	AgentService_SystemStats_FullMethodName       = "/agent.v1.AgentService/SystemStats"
	AgentService_ProcessList_FullMethodName       = "/agent.v1.AgentService/ProcessList"
	AgentService_ProcessKill_FullMethodName       = "/agent.v1.AgentService/ProcessKill"
	AgentService_Ping_FullMethodName              = "/agent.v1.AgentService/Ping"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService is the gRPC service exposed by the OpenDeploy Agent.
// The Core calls these methods to perform privileged system operations.
// The Agent validates every request against an allowlist before execution.
type AgentServiceClient interface {
	// ── Systemd service management ─────────────────────────────────────────
	ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error)
	ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error)
	ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	ServiceStreamLogs(ctx context.Context, in *ServiceStreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	FileLogs(ctx context.Context, in *FileLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error)
	CommandExecute(ctx context.Context, in *CommandExecuteRequest, opts ...grpc.CallOption) (*CommandExecuteResponse, error)
	// ── Package management ─────────────────────────────────────────────────
	PackageInstall(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOutput], error)
	PackageRemove(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOutput], error)
	PackageUpdate(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOutput], error)
	PackageStatus(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (*PackageStatusResponse, error)
	// ── File system ────────────────────────────────────────────────────────
	FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error)
	FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error)
	FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error)
	DirCreate(ctx context.Context, in *DirCreateRequest, opts ...grpc.CallOption) (*DirCreateResponse, error)
	DirList(ctx context.Context, in *DirListRequest, opts ...grpc.CallOption) (*DirListResponse, error)
	FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*FileRenameResponse, error)
	FileCopy(ctx context.Context, in *FileCopyRequest, opts ...grpc.CallOption) (*FileCopyResponse, error)
	FileChmod(ctx context.Context, in *FileChmodRequest, opts ...grpc.CallOption) (*FileChmodResponse, error)
	FileChown(ctx context.Context, in *FileChownRequest, opts ...grpc.CallOption) (*FileChownResponse, error)
	ArchiveCreate(ctx context.Context, in *ArchiveCreateRequest, opts ...grpc.CallOption) (*ArchiveCreateResponse, error)
	ArchiveExtract(ctx context.Context, in *ArchiveExtractRequest, opts ...grpc.CallOption) (*ArchiveExtractResponse, error)
	FileUploadStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileUploadRequest, FileUploadResponse], error)
	// Typed Nginx site configuration. The Agent renders, validates and applies
	// the configuration atomically; Core cannot execute arbitrary commands.
	NginxSiteApply(ctx context.Context, in *NginxSiteApplyRequest, opts ...grpc.CallOption) (*NginxSiteApplyResponse, error)
	// ── Firewall ───────────────────────────────────────────────────────────
	FirewallRule(ctx context.Context, in *FirewallRuleRequest, opts ...grpc.CallOption) (*FirewallRuleResponse, error)
	FirewallDelete(ctx context.Context, in *FirewallDeleteRequest, opts ...grpc.CallOption) (*FirewallDeleteResponse, error)
	FirewallList(ctx context.Context, in *FirewallListRequest, opts ...grpc.CallOption) (*FirewallListResponse, error)
	FirewallStatus(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error)
	FirewallToggle(ctx context.Context, in *FirewallToggleRequest, opts ...grpc.CallOption) (*FirewallToggleResponse, error)
	FirewallReset(ctx context.Context, in *FirewallResetRequest, opts ...grpc.CallOption) (*FirewallResetResponse, error)
	// ── Cron management ──────────────────────────────────────────────────
	CronList(ctx context.Context, in *CronListRequest, opts ...grpc.CallOption) (*CronListResponse, error)
	CronGet(ctx context.Context, in *CronGetRequest, opts ...grpc.CallOption) (*CronJob, error)
	CronCreate(ctx context.Context, in *CronMutationRequest, opts ...grpc.CallOption) (*CronJob, error)
	CronUpdate(ctx context.Context, in *CronMutationRequest, opts ...grpc.CallOption) (*CronJob, error)
	CronDelete(ctx context.Context, in *CronIDRequest, opts ...grpc.CallOption) (*CronOperationResponse, error)
	CronEnable(ctx context.Context, in *CronIDRequest, opts ...grpc.CallOption) (*CronJob, error)
	CronDisable(ctx context.Context, in *CronIDRequest, opts ...grpc.CallOption) (*CronJob, error)
	CronRun(ctx context.Context, in *CronRunRequest, opts ...grpc.CallOption) (*CronRunRecord, error)
	CronHistory(ctx context.Context, in *CronHistoryRequest, opts ...grpc.CallOption) (*CronHistoryResponse, error)
	CronLogs(ctx context.Context, in *CronLogsRequest, opts ...grpc.CallOption) (*CronHistoryResponse, error)
	CronImport(ctx context.Context, in *CronImportRequest, opts ...grpc.CallOption) (*CronListResponse, error)
	CronExport(ctx context.Context, in *CronExportRequest, opts ...grpc.CallOption) (*CronExportResponse, error)
	CronValidate(ctx context.Context, in *CronMutationRequest, opts ...grpc.CallOption) (*CronValidationResponse, error)
	// ── System information ─────────────────────────────────────────────────
	SystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error)
	ProcessList(ctx context.Context, in *ProcessListRequest, opts ...grpc.CallOption) (*ProcessListResponse, error)
	ProcessKill(ctx context.Context, in *ProcessKillRequest, opts ...grpc.CallOption) (*ProcessKillResponse, error)
	// ── Health check ───────────────────────────────────────────────────────
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceActionResponse)
	err := c.cc.Invoke(ctx, AgentService_ServiceAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ServiceLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ServiceLogsClient = grpc.ServerStreamingClient[LogLine]

func (c *agentServiceClient) ServiceStreamLogs(ctx context.Context, in *ServiceStreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_ServiceStreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServiceStreamLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ServiceStreamLogsClient = grpc.ServerStreamingClient[LogLine]

func (c *agentServiceClient) FileLogs(ctx context.Context, in *FileLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_FileLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_FileLogsClient = grpc.ServerStreamingClient[LogLine]

func (c *agentServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogLine], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[3], AgentService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogLine]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsClient = grpc.ServerStreamingClient[LogLine]

func (c *agentServiceClient) CommandExecute(ctx context.Context, in *CommandExecuteRequest, opts ...grpc.CallOption) (*CommandExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandExecuteResponse)
	err := c.cc.Invoke(ctx, AgentService_CommandExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PackageInstall(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[4], AgentService_PackageInstall_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageRequest, PackageOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PackageInstallClient = grpc.ServerStreamingClient[PackageOutput]

func (c *agentServiceClient) PackageRemove(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[5], AgentService_PackageRemove_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageRequest, PackageOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PackageRemoveClient = grpc.ServerStreamingClient[PackageOutput]

func (c *agentServiceClient) PackageUpdate(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PackageOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[6], AgentService_PackageUpdate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PackageRequest, PackageOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PackageUpdateClient = grpc.ServerStreamingClient[PackageOutput]

func (c *agentServiceClient) PackageStatus(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (*PackageStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PackageStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_PackageStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileReadResponse)
	err := c.cc.Invoke(ctx, AgentService_FileRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileWriteResponse)
	err := c.cc.Invoke(ctx, AgentService_FileWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileDeleteResponse)
	err := c.cc.Invoke(ctx, AgentService_FileDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DirCreate(ctx context.Context, in *DirCreateRequest, opts ...grpc.CallOption) (*DirCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirCreateResponse)
	err := c.cc.Invoke(ctx, AgentService_DirCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DirList(ctx context.Context, in *DirListRequest, opts ...grpc.CallOption) (*DirListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DirListResponse)
	err := c.cc.Invoke(ctx, AgentService_DirList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*FileRenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileRenameResponse)
	err := c.cc.Invoke(ctx, AgentService_FileRename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileCopy(ctx context.Context, in *FileCopyRequest, opts ...grpc.CallOption) (*FileCopyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileCopyResponse)
	err := c.cc.Invoke(ctx, AgentService_FileCopy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileChmod(ctx context.Context, in *FileChmodRequest, opts ...grpc.CallOption) (*FileChmodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileChmodResponse)
	err := c.cc.Invoke(ctx, AgentService_FileChmod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileChown(ctx context.Context, in *FileChownRequest, opts ...grpc.CallOption) (*FileChownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileChownResponse)
	err := c.cc.Invoke(ctx, AgentService_FileChown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ArchiveCreate(ctx context.Context, in *ArchiveCreateRequest, opts ...grpc.CallOption) (*ArchiveCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveCreateResponse)
	err := c.cc.Invoke(ctx, AgentService_ArchiveCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ArchiveExtract(ctx context.Context, in *ArchiveExtractRequest, opts ...grpc.CallOption) (*ArchiveExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveExtractResponse)
	err := c.cc.Invoke(ctx, AgentService_ArchiveExtract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileUploadStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[FileUploadRequest, FileUploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[7], AgentService_FileUploadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FileUploadRequest, FileUploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_FileUploadStreamClient = grpc.ClientStreamingClient[FileUploadRequest, FileUploadResponse]

func (c *agentServiceClient) NginxSiteApply(ctx context.Context, in *NginxSiteApplyRequest, opts ...grpc.CallOption) (*NginxSiteApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NginxSiteApplyResponse)
	err := c.cc.Invoke(ctx, AgentService_NginxSiteApply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallRule(ctx context.Context, in *FirewallRuleRequest, opts ...grpc.CallOption) (*FirewallRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallRuleResponse)
	err := c.cc.Invoke(ctx, AgentService_FirewallRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallDelete(ctx context.Context, in *FirewallDeleteRequest, opts ...grpc.CallOption) (*FirewallDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallDeleteResponse)
	err := c.cc.Invoke(ctx, AgentService_FirewallDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallList(ctx context.Context, in *FirewallListRequest, opts ...grpc.CallOption) (*FirewallListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallListResponse)
	err := c.cc.Invoke(ctx, AgentService_FirewallList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallStatus(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallStatusResponse)
	err := c.cc.Invoke(ctx, AgentService_FirewallStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallToggle(ctx context.Context, in *FirewallToggleRequest, opts ...grpc.CallOption) (*FirewallToggleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallToggleResponse)
	err := c.cc.Invoke(ctx, AgentService_FirewallToggle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallReset(ctx context.Context, in *FirewallResetRequest, opts ...grpc.CallOption) (*FirewallResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FirewallResetResponse)
	err := c.cc.Invoke(ctx, AgentService_FirewallReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronList(ctx context.Context, in *CronListRequest, opts ...grpc.CallOption) (*CronListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronListResponse)
	err := c.cc.Invoke(ctx, AgentService_CronList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronGet(ctx context.Context, in *CronGetRequest, opts ...grpc.CallOption) (*CronJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJob)
	err := c.cc.Invoke(ctx, AgentService_CronGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronCreate(ctx context.Context, in *CronMutationRequest, opts ...grpc.CallOption) (*CronJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJob)
	err := c.cc.Invoke(ctx, AgentService_CronCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronUpdate(ctx context.Context, in *CronMutationRequest, opts ...grpc.CallOption) (*CronJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJob)
	err := c.cc.Invoke(ctx, AgentService_CronUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronDelete(ctx context.Context, in *CronIDRequest, opts ...grpc.CallOption) (*CronOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronOperationResponse)
	err := c.cc.Invoke(ctx, AgentService_CronDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronEnable(ctx context.Context, in *CronIDRequest, opts ...grpc.CallOption) (*CronJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJob)
	err := c.cc.Invoke(ctx, AgentService_CronEnable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronDisable(ctx context.Context, in *CronIDRequest, opts ...grpc.CallOption) (*CronJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronJob)
	err := c.cc.Invoke(ctx, AgentService_CronDisable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronRun(ctx context.Context, in *CronRunRequest, opts ...grpc.CallOption) (*CronRunRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronRunRecord)
	err := c.cc.Invoke(ctx, AgentService_CronRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronHistory(ctx context.Context, in *CronHistoryRequest, opts ...grpc.CallOption) (*CronHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronHistoryResponse)
	err := c.cc.Invoke(ctx, AgentService_CronHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronLogs(ctx context.Context, in *CronLogsRequest, opts ...grpc.CallOption) (*CronHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronHistoryResponse)
	err := c.cc.Invoke(ctx, AgentService_CronLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronImport(ctx context.Context, in *CronImportRequest, opts ...grpc.CallOption) (*CronListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronListResponse)
	err := c.cc.Invoke(ctx, AgentService_CronImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronExport(ctx context.Context, in *CronExportRequest, opts ...grpc.CallOption) (*CronExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronExportResponse)
	err := c.cc.Invoke(ctx, AgentService_CronExport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) CronValidate(ctx context.Context, in *CronMutationRequest, opts ...grpc.CallOption) (*CronValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CronValidationResponse)
	err := c.cc.Invoke(ctx, AgentService_CronValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatsResponse)
	err := c.cc.Invoke(ctx, AgentService_SystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ProcessList(ctx context.Context, in *ProcessListRequest, opts ...grpc.CallOption) (*ProcessListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessListResponse)
	err := c.cc.Invoke(ctx, AgentService_ProcessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ProcessKill(ctx context.Context, in *ProcessKillRequest, opts ...grpc.CallOption) (*ProcessKillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessKillResponse)
	err := c.cc.Invoke(ctx, AgentService_ProcessKill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService is the gRPC service exposed by the OpenDeploy Agent.
// The Core calls these methods to perform privileged system operations.
// The Agent validates every request against an allowlist before execution.
type AgentServiceServer interface {
	// ── Systemd service management ─────────────────────────────────────────
	ServiceAction(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error)
	ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error)
	ServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	ServiceStreamLogs(*ServiceStreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	FileLogs(*FileLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error
	CommandExecute(context.Context, *CommandExecuteRequest) (*CommandExecuteResponse, error)
	// ── Package management ─────────────────────────────────────────────────
	PackageInstall(*PackageRequest, grpc.ServerStreamingServer[PackageOutput]) error
	PackageRemove(*PackageRequest, grpc.ServerStreamingServer[PackageOutput]) error
	PackageUpdate(*PackageRequest, grpc.ServerStreamingServer[PackageOutput]) error
	PackageStatus(context.Context, *PackageRequest) (*PackageStatusResponse, error)
	// ── File system ────────────────────────────────────────────────────────
	FileRead(context.Context, *FileReadRequest) (*FileReadResponse, error)
	FileWrite(context.Context, *FileWriteRequest) (*FileWriteResponse, error)
	FileDelete(context.Context, *FileDeleteRequest) (*FileDeleteResponse, error)
	DirCreate(context.Context, *DirCreateRequest) (*DirCreateResponse, error)
	DirList(context.Context, *DirListRequest) (*DirListResponse, error)
	FileRename(context.Context, *FileRenameRequest) (*FileRenameResponse, error)
	FileCopy(context.Context, *FileCopyRequest) (*FileCopyResponse, error)
	FileChmod(context.Context, *FileChmodRequest) (*FileChmodResponse, error)
	FileChown(context.Context, *FileChownRequest) (*FileChownResponse, error)
	ArchiveCreate(context.Context, *ArchiveCreateRequest) (*ArchiveCreateResponse, error)
	ArchiveExtract(context.Context, *ArchiveExtractRequest) (*ArchiveExtractResponse, error)
	FileUploadStream(grpc.ClientStreamingServer[FileUploadRequest, FileUploadResponse]) error
	// Typed Nginx site configuration. The Agent renders, validates and applies
	// the configuration atomically; Core cannot execute arbitrary commands.
	NginxSiteApply(context.Context, *NginxSiteApplyRequest) (*NginxSiteApplyResponse, error)
	// ── Firewall ───────────────────────────────────────────────────────────
	FirewallRule(context.Context, *FirewallRuleRequest) (*FirewallRuleResponse, error)
	FirewallDelete(context.Context, *FirewallDeleteRequest) (*FirewallDeleteResponse, error)
	FirewallList(context.Context, *FirewallListRequest) (*FirewallListResponse, error)
	FirewallStatus(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error)
	FirewallToggle(context.Context, *FirewallToggleRequest) (*FirewallToggleResponse, error)
	FirewallReset(context.Context, *FirewallResetRequest) (*FirewallResetResponse, error)
	// ── Cron management ──────────────────────────────────────────────────
	CronList(context.Context, *CronListRequest) (*CronListResponse, error)
	CronGet(context.Context, *CronGetRequest) (*CronJob, error)
	CronCreate(context.Context, *CronMutationRequest) (*CronJob, error)
	CronUpdate(context.Context, *CronMutationRequest) (*CronJob, error)
	CronDelete(context.Context, *CronIDRequest) (*CronOperationResponse, error)
	CronEnable(context.Context, *CronIDRequest) (*CronJob, error)
	CronDisable(context.Context, *CronIDRequest) (*CronJob, error)
	CronRun(context.Context, *CronRunRequest) (*CronRunRecord, error)
	CronHistory(context.Context, *CronHistoryRequest) (*CronHistoryResponse, error)
	CronLogs(context.Context, *CronLogsRequest) (*CronHistoryResponse, error)
	CronImport(context.Context, *CronImportRequest) (*CronListResponse, error)
	CronExport(context.Context, *CronExportRequest) (*CronExportResponse, error)
	CronValidate(context.Context, *CronMutationRequest) (*CronValidationResponse, error)
	// ── System information ─────────────────────────────────────────────────
	SystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error)
	ProcessList(context.Context, *ProcessListRequest) (*ProcessListResponse, error)
	ProcessKill(context.Context, *ProcessKillRequest) (*ProcessKillResponse, error)
	// ── Health check ───────────────────────────────────────────────────────
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ServiceAction(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServiceAction not implemented")
}
func (UnimplementedAgentServiceServer) ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ServiceStatus not implemented")
}
func (UnimplementedAgentServiceServer) ServiceLogs(*ServiceLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method ServiceLogs not implemented")
}
func (UnimplementedAgentServiceServer) ServiceStreamLogs(*ServiceStreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method ServiceStreamLogs not implemented")
}
func (UnimplementedAgentServiceServer) FileLogs(*FileLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method FileLogs not implemented")
}
func (UnimplementedAgentServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogLine]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedAgentServiceServer) CommandExecute(context.Context, *CommandExecuteRequest) (*CommandExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommandExecute not implemented")
}
func (UnimplementedAgentServiceServer) PackageInstall(*PackageRequest, grpc.ServerStreamingServer[PackageOutput]) error {
	return status.Error(codes.Unimplemented, "method PackageInstall not implemented")
}
func (UnimplementedAgentServiceServer) PackageRemove(*PackageRequest, grpc.ServerStreamingServer[PackageOutput]) error {
	return status.Error(codes.Unimplemented, "method PackageRemove not implemented")
}
func (UnimplementedAgentServiceServer) PackageUpdate(*PackageRequest, grpc.ServerStreamingServer[PackageOutput]) error {
	return status.Error(codes.Unimplemented, "method PackageUpdate not implemented")
}
func (UnimplementedAgentServiceServer) PackageStatus(context.Context, *PackageRequest) (*PackageStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PackageStatus not implemented")
}
func (UnimplementedAgentServiceServer) FileRead(context.Context, *FileReadRequest) (*FileReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileRead not implemented")
}
func (UnimplementedAgentServiceServer) FileWrite(context.Context, *FileWriteRequest) (*FileWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileWrite not implemented")
}
func (UnimplementedAgentServiceServer) FileDelete(context.Context, *FileDeleteRequest) (*FileDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileDelete not implemented")
}
func (UnimplementedAgentServiceServer) DirCreate(context.Context, *DirCreateRequest) (*DirCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirCreate not implemented")
}
func (UnimplementedAgentServiceServer) DirList(context.Context, *DirListRequest) (*DirListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DirList not implemented")
}
func (UnimplementedAgentServiceServer) FileRename(context.Context, *FileRenameRequest) (*FileRenameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileRename not implemented")
}
func (UnimplementedAgentServiceServer) FileCopy(context.Context, *FileCopyRequest) (*FileCopyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileCopy not implemented")
}
func (UnimplementedAgentServiceServer) FileChmod(context.Context, *FileChmodRequest) (*FileChmodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileChmod not implemented")
}
func (UnimplementedAgentServiceServer) FileChown(context.Context, *FileChownRequest) (*FileChownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FileChown not implemented")
}
func (UnimplementedAgentServiceServer) ArchiveCreate(context.Context, *ArchiveCreateRequest) (*ArchiveCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveCreate not implemented")
}
func (UnimplementedAgentServiceServer) ArchiveExtract(context.Context, *ArchiveExtractRequest) (*ArchiveExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveExtract not implemented")
}
func (UnimplementedAgentServiceServer) FileUploadStream(grpc.ClientStreamingServer[FileUploadRequest, FileUploadResponse]) error {
	return status.Error(codes.Unimplemented, "method FileUploadStream not implemented")
}
func (UnimplementedAgentServiceServer) NginxSiteApply(context.Context, *NginxSiteApplyRequest) (*NginxSiteApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NginxSiteApply not implemented")
}
func (UnimplementedAgentServiceServer) FirewallRule(context.Context, *FirewallRuleRequest) (*FirewallRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FirewallRule not implemented")
}
func (UnimplementedAgentServiceServer) FirewallDelete(context.Context, *FirewallDeleteRequest) (*FirewallDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FirewallDelete not implemented")
}
func (UnimplementedAgentServiceServer) FirewallList(context.Context, *FirewallListRequest) (*FirewallListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FirewallList not implemented")
}
func (UnimplementedAgentServiceServer) FirewallStatus(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FirewallStatus not implemented")
}
func (UnimplementedAgentServiceServer) FirewallToggle(context.Context, *FirewallToggleRequest) (*FirewallToggleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FirewallToggle not implemented")
}
func (UnimplementedAgentServiceServer) FirewallReset(context.Context, *FirewallResetRequest) (*FirewallResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FirewallReset not implemented")
}
func (UnimplementedAgentServiceServer) CronList(context.Context, *CronListRequest) (*CronListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronList not implemented")
}
func (UnimplementedAgentServiceServer) CronGet(context.Context, *CronGetRequest) (*CronJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CronGet not implemented")
}
func (UnimplementedAgentServiceServer) CronCreate(context.Context, *CronMutationRequest) (*CronJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CronCreate not implemented")
}
func (UnimplementedAgentServiceServer) CronUpdate(context.Context, *CronMutationRequest) (*CronJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CronUpdate not implemented")
}
func (UnimplementedAgentServiceServer) CronDelete(context.Context, *CronIDRequest) (*CronOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronDelete not implemented")
}
func (UnimplementedAgentServiceServer) CronEnable(context.Context, *CronIDRequest) (*CronJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CronEnable not implemented")
}
func (UnimplementedAgentServiceServer) CronDisable(context.Context, *CronIDRequest) (*CronJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CronDisable not implemented")
}
func (UnimplementedAgentServiceServer) CronRun(context.Context, *CronRunRequest) (*CronRunRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method CronRun not implemented")
}
func (UnimplementedAgentServiceServer) CronHistory(context.Context, *CronHistoryRequest) (*CronHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronHistory not implemented")
}
func (UnimplementedAgentServiceServer) CronLogs(context.Context, *CronLogsRequest) (*CronHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronLogs not implemented")
}
func (UnimplementedAgentServiceServer) CronImport(context.Context, *CronImportRequest) (*CronListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronImport not implemented")
}
func (UnimplementedAgentServiceServer) CronExport(context.Context, *CronExportRequest) (*CronExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronExport not implemented")
}
func (UnimplementedAgentServiceServer) CronValidate(context.Context, *CronMutationRequest) (*CronValidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CronValidate not implemented")
}
func (UnimplementedAgentServiceServer) SystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SystemStats not implemented")
}
func (UnimplementedAgentServiceServer) ProcessList(context.Context, *ProcessListRequest) (*ProcessListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessList not implemented")
}
func (UnimplementedAgentServiceServer) ProcessKill(context.Context, *ProcessKillRequest) (*ProcessKillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessKill not implemented")
}
func (UnimplementedAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ServiceAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ServiceAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ServiceAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ServiceAction(ctx, req.(*ServiceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ServiceStatus(ctx, req.(*ServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ServiceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ServiceLogs(m, &grpc.GenericServerStream[ServiceLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ServiceLogsServer = grpc.ServerStreamingServer[LogLine]

func _AgentService_ServiceStreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceStreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ServiceStreamLogs(m, &grpc.GenericServerStream[ServiceStreamLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ServiceStreamLogsServer = grpc.ServerStreamingServer[LogLine]

func _AgentService_FileLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).FileLogs(m, &grpc.GenericServerStream[FileLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_FileLogsServer = grpc.ServerStreamingServer[LogLine]

func _AgentService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogLine]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StreamLogsServer = grpc.ServerStreamingServer[LogLine]

func _AgentService_CommandExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CommandExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CommandExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CommandExecute(ctx, req.(*CommandExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PackageInstall_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).PackageInstall(m, &grpc.GenericServerStream[PackageRequest, PackageOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PackageInstallServer = grpc.ServerStreamingServer[PackageOutput]

func _AgentService_PackageRemove_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).PackageRemove(m, &grpc.GenericServerStream[PackageRequest, PackageOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PackageRemoveServer = grpc.ServerStreamingServer[PackageOutput]

func _AgentService_PackageUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).PackageUpdate(m, &grpc.GenericServerStream[PackageRequest, PackageOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_PackageUpdateServer = grpc.ServerStreamingServer[PackageOutput]

func _AgentService_PackageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PackageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_PackageStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PackageStatus(ctx, req.(*PackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileRead(ctx, req.(*FileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileWrite(ctx, req.(*FileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileDelete(ctx, req.(*FileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DirCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DirCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DirCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DirCreate(ctx, req.(*DirCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DirList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DirList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DirList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DirList(ctx, req.(*DirListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileRename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileRename(ctx, req.(*FileRenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileCopy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileCopy(ctx, req.(*FileCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileChmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileChmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileChmod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileChmod(ctx, req.(*FileChmodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileChown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileChown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FileChown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileChown(ctx, req.(*FileChownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ArchiveCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ArchiveCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ArchiveCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ArchiveCreate(ctx, req.(*ArchiveCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ArchiveExtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ArchiveExtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ArchiveExtract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ArchiveExtract(ctx, req.(*ArchiveExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileUploadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).FileUploadStream(&grpc.GenericServerStream[FileUploadRequest, FileUploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_FileUploadStreamServer = grpc.ClientStreamingServer[FileUploadRequest, FileUploadResponse]

func _AgentService_NginxSiteApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NginxSiteApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).NginxSiteApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_NginxSiteApply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).NginxSiteApply(ctx, req.(*NginxSiteApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FirewallRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallRule(ctx, req.(*FirewallRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FirewallDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallDelete(ctx, req.(*FirewallDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FirewallList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallList(ctx, req.(*FirewallListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FirewallStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallStatus(ctx, req.(*FirewallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallToggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallToggleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallToggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FirewallToggle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallToggle(ctx, req.(*FirewallToggleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_FirewallReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallReset(ctx, req.(*FirewallResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronList(ctx, req.(*CronListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronGet(ctx, req.(*CronGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronCreate(ctx, req.(*CronMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronUpdate(ctx, req.(*CronMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronDelete(ctx, req.(*CronIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronEnable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronEnable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronEnable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronEnable(ctx, req.(*CronIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronDisable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronDisable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronDisable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronDisable(ctx, req.(*CronIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronRun(ctx, req.(*CronRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronHistory(ctx, req.(*CronHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronLogs(ctx, req.(*CronLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronImport(ctx, req.(*CronImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronExport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronExport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronExport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronExport(ctx, req.(*CronExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_CronValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CronMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CronValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_CronValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CronValidate(ctx, req.(*CronMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SystemStats(ctx, req.(*SystemStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ProcessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ProcessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ProcessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ProcessList(ctx, req.(*ProcessListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ProcessKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ProcessKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ProcessKill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ProcessKill(ctx, req.(*ProcessKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceAction",
			Handler:    _AgentService_ServiceAction_Handler,
		},
		{
			MethodName: "ServiceStatus",
			Handler:    _AgentService_ServiceStatus_Handler,
		},
		{
			MethodName: "CommandExecute",
			Handler:    _AgentService_CommandExecute_Handler,
		},
		{
			MethodName: "PackageStatus",
			Handler:    _AgentService_PackageStatus_Handler,
		},
		{
			MethodName: "FileRead",
			Handler:    _AgentService_FileRead_Handler,
		},
		{
			MethodName: "FileWrite",
			Handler:    _AgentService_FileWrite_Handler,
		},
		{
			MethodName: "FileDelete",
			Handler:    _AgentService_FileDelete_Handler,
		},
		{
			MethodName: "DirCreate",
			Handler:    _AgentService_DirCreate_Handler,
		},
		{
			MethodName: "DirList",
			Handler:    _AgentService_DirList_Handler,
		},
		{
			MethodName: "FileRename",
			Handler:    _AgentService_FileRename_Handler,
		},
		{
			MethodName: "FileCopy",
			Handler:    _AgentService_FileCopy_Handler,
		},
		{
			MethodName: "FileChmod",
			Handler:    _AgentService_FileChmod_Handler,
		},
		{
			MethodName: "FileChown",
			Handler:    _AgentService_FileChown_Handler,
		},
		{
			MethodName: "ArchiveCreate",
			Handler:    _AgentService_ArchiveCreate_Handler,
		},
		{
			MethodName: "ArchiveExtract",
			Handler:    _AgentService_ArchiveExtract_Handler,
		},
		{
			MethodName: "NginxSiteApply",
			Handler:    _AgentService_NginxSiteApply_Handler,
		},
		{
			MethodName: "FirewallRule",
			Handler:    _AgentService_FirewallRule_Handler,
		},
		{
			MethodName: "FirewallDelete",
			Handler:    _AgentService_FirewallDelete_Handler,
		},
		{
			MethodName: "FirewallList",
			Handler:    _AgentService_FirewallList_Handler,
		},
		{
			MethodName: "FirewallStatus",
			Handler:    _AgentService_FirewallStatus_Handler,
		},
		{
			MethodName: "FirewallToggle",
			Handler:    _AgentService_FirewallToggle_Handler,
		},
		{
			MethodName: "FirewallReset",
			Handler:    _AgentService_FirewallReset_Handler,
		},
		{
			MethodName: "CronList",
			Handler:    _AgentService_CronList_Handler,
		},
		{
			MethodName: "CronGet",
			Handler:    _AgentService_CronGet_Handler,
		},
		{
			MethodName: "CronCreate",
			Handler:    _AgentService_CronCreate_Handler,
		},
		{
			MethodName: "CronUpdate",
			Handler:    _AgentService_CronUpdate_Handler,
		},
		{
			MethodName: "CronDelete",
			Handler:    _AgentService_CronDelete_Handler,
		},
		{
			MethodName: "CronEnable",
			Handler:    _AgentService_CronEnable_Handler,
		},
		{
			MethodName: "CronDisable",
			Handler:    _AgentService_CronDisable_Handler,
		},
		{
			MethodName: "CronRun",
			Handler:    _AgentService_CronRun_Handler,
		},
		{
			MethodName: "CronHistory",
			Handler:    _AgentService_CronHistory_Handler,
		},
		{
			MethodName: "CronLogs",
			Handler:    _AgentService_CronLogs_Handler,
		},
		{
			MethodName: "CronImport",
			Handler:    _AgentService_CronImport_Handler,
		},
		{
			MethodName: "CronExport",
			Handler:    _AgentService_CronExport_Handler,
		},
		{
			MethodName: "CronValidate",
			Handler:    _AgentService_CronValidate_Handler,
		},
		{
			MethodName: "SystemStats",
			Handler:    _AgentService_SystemStats_Handler,
		},
		{
			MethodName: "ProcessList",
			Handler:    _AgentService_ProcessList_Handler,
		},
		{
			MethodName: "ProcessKill",
			Handler:    _AgentService_ProcessKill_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServiceLogs",
			Handler:       _AgentService_ServiceLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ServiceStreamLogs",
			Handler:       _AgentService_ServiceStreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileLogs",
			Handler:       _AgentService_FileLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamLogs",
			Handler:       _AgentService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PackageInstall",
			Handler:       _AgentService_PackageInstall_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PackageRemove",
			Handler:       _AgentService_PackageRemove_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PackageUpdate",
			Handler:       _AgentService_PackageUpdate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileUploadStream",
			Handler:       _AgentService_FileUploadStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
