// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	// ── Systemd service management ─────────────────────────────────────────
	ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error)
	ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error)
	ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (AgentService_ServiceLogsClient, error)
	FileLogs(ctx context.Context, in *FileLogsRequest, opts ...grpc.CallOption) (AgentService_FileLogsClient, error)
	CommandExecute(ctx context.Context, in *CommandExecuteRequest, opts ...grpc.CallOption) (*CommandExecuteResponse, error)
	// ── Package management ─────────────────────────────────────────────────
	PackageInstall(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (AgentService_PackageInstallClient, error)
	PackageRemove(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (AgentService_PackageRemoveClient, error)
	PackageUpdate(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (AgentService_PackageUpdateClient, error)
	PackageStatus(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (*PackageStatusResponse, error)
	// ── File system ────────────────────────────────────────────────────────
	FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error)
	FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error)
	FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error)
	DirCreate(ctx context.Context, in *DirCreateRequest, opts ...grpc.CallOption) (*DirCreateResponse, error)
	DirList(ctx context.Context, in *DirListRequest, opts ...grpc.CallOption) (*DirListResponse, error)
	FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*FileRenameResponse, error)
	FileCopy(ctx context.Context, in *FileCopyRequest, opts ...grpc.CallOption) (*FileCopyResponse, error)
	FileChmod(ctx context.Context, in *FileChmodRequest, opts ...grpc.CallOption) (*FileChmodResponse, error)
	FileChown(ctx context.Context, in *FileChownRequest, opts ...grpc.CallOption) (*FileChownResponse, error)
	ArchiveCreate(ctx context.Context, in *ArchiveCreateRequest, opts ...grpc.CallOption) (*ArchiveCreateResponse, error)
	ArchiveExtract(ctx context.Context, in *ArchiveExtractRequest, opts ...grpc.CallOption) (*ArchiveExtractResponse, error)
	FileUploadStream(ctx context.Context, opts ...grpc.CallOption) (AgentService_FileUploadStreamClient, error)
	// Typed Nginx site configuration. The Agent renders, validates and applies
	// the configuration atomically; Core cannot execute arbitrary commands.
	NginxSiteApply(ctx context.Context, in *NginxSiteApplyRequest, opts ...grpc.CallOption) (*NginxSiteApplyResponse, error)
	// ── Firewall ───────────────────────────────────────────────────────────
	FirewallRule(ctx context.Context, in *FirewallRuleRequest, opts ...grpc.CallOption) (*FirewallRuleResponse, error)
	FirewallDelete(ctx context.Context, in *FirewallDeleteRequest, opts ...grpc.CallOption) (*FirewallDeleteResponse, error)
	FirewallList(ctx context.Context, in *FirewallListRequest, opts ...grpc.CallOption) (*FirewallListResponse, error)
	FirewallStatus(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error)
	FirewallToggle(ctx context.Context, in *FirewallToggleRequest, opts ...grpc.CallOption) (*FirewallToggleResponse, error)
	FirewallReset(ctx context.Context, in *FirewallResetRequest, opts ...grpc.CallOption) (*FirewallResetResponse, error)
	// ── System information ─────────────────────────────────────────────────
	SystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error)
	// ── Health check ───────────────────────────────────────────────────────
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ServiceAction(ctx context.Context, in *ServiceActionRequest, opts ...grpc.CallOption) (*ServiceActionResponse, error) {
	out := new(ServiceActionResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/ServiceAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ServiceStatus(ctx context.Context, in *ServiceStatusRequest, opts ...grpc.CallOption) (*ServiceStatusResponse, error) {
	out := new(ServiceStatusResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/ServiceStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ServiceLogs(ctx context.Context, in *ServiceLogsRequest, opts ...grpc.CallOption) (AgentService_ServiceLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], "/agent.v1.AgentService/ServiceLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceServiceLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_ServiceLogsClient interface {
	Recv() (*LogLine, error)
	grpc.ClientStream
}

type agentServiceServiceLogsClient struct {
	grpc.ClientStream
}

func (x *agentServiceServiceLogsClient) Recv() (*LogLine, error) {
	m := new(LogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) FileLogs(ctx context.Context, in *FileLogsRequest, opts ...grpc.CallOption) (AgentService_FileLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], "/agent.v1.AgentService/FileLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceFileLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_FileLogsClient interface {
	Recv() (*LogLine, error)
	grpc.ClientStream
}

type agentServiceFileLogsClient struct {
	grpc.ClientStream
}

func (x *agentServiceFileLogsClient) Recv() (*LogLine, error) {
	m := new(LogLine)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) CommandExecute(ctx context.Context, in *CommandExecuteRequest, opts ...grpc.CallOption) (*CommandExecuteResponse, error) {
	out := new(CommandExecuteResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/CommandExecute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) PackageInstall(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (AgentService_PackageInstallClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], "/agent.v1.AgentService/PackageInstall", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServicePackageInstallClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_PackageInstallClient interface {
	Recv() (*PackageOutput, error)
	grpc.ClientStream
}

type agentServicePackageInstallClient struct {
	grpc.ClientStream
}

func (x *agentServicePackageInstallClient) Recv() (*PackageOutput, error) {
	m := new(PackageOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) PackageRemove(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (AgentService_PackageRemoveClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[3], "/agent.v1.AgentService/PackageRemove", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServicePackageRemoveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_PackageRemoveClient interface {
	Recv() (*PackageOutput, error)
	grpc.ClientStream
}

type agentServicePackageRemoveClient struct {
	grpc.ClientStream
}

func (x *agentServicePackageRemoveClient) Recv() (*PackageOutput, error) {
	m := new(PackageOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) PackageUpdate(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (AgentService_PackageUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[4], "/agent.v1.AgentService/PackageUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServicePackageUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AgentService_PackageUpdateClient interface {
	Recv() (*PackageOutput, error)
	grpc.ClientStream
}

type agentServicePackageUpdateClient struct {
	grpc.ClientStream
}

func (x *agentServicePackageUpdateClient) Recv() (*PackageOutput, error) {
	m := new(PackageOutput)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) PackageStatus(ctx context.Context, in *PackageRequest, opts ...grpc.CallOption) (*PackageStatusResponse, error) {
	out := new(PackageStatusResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/PackageStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileRead(ctx context.Context, in *FileReadRequest, opts ...grpc.CallOption) (*FileReadResponse, error) {
	out := new(FileReadResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FileRead", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileWrite(ctx context.Context, in *FileWriteRequest, opts ...grpc.CallOption) (*FileWriteResponse, error) {
	out := new(FileWriteResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FileWrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*FileDeleteResponse, error) {
	out := new(FileDeleteResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FileDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DirCreate(ctx context.Context, in *DirCreateRequest, opts ...grpc.CallOption) (*DirCreateResponse, error) {
	out := new(DirCreateResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/DirCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DirList(ctx context.Context, in *DirListRequest, opts ...grpc.CallOption) (*DirListResponse, error) {
	out := new(DirListResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/DirList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileRename(ctx context.Context, in *FileRenameRequest, opts ...grpc.CallOption) (*FileRenameResponse, error) {
	out := new(FileRenameResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FileRename", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileCopy(ctx context.Context, in *FileCopyRequest, opts ...grpc.CallOption) (*FileCopyResponse, error) {
	out := new(FileCopyResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FileCopy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileChmod(ctx context.Context, in *FileChmodRequest, opts ...grpc.CallOption) (*FileChmodResponse, error) {
	out := new(FileChmodResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FileChmod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileChown(ctx context.Context, in *FileChownRequest, opts ...grpc.CallOption) (*FileChownResponse, error) {
	out := new(FileChownResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FileChown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ArchiveCreate(ctx context.Context, in *ArchiveCreateRequest, opts ...grpc.CallOption) (*ArchiveCreateResponse, error) {
	out := new(ArchiveCreateResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/ArchiveCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ArchiveExtract(ctx context.Context, in *ArchiveExtractRequest, opts ...grpc.CallOption) (*ArchiveExtractResponse, error) {
	out := new(ArchiveExtractResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/ArchiveExtract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FileUploadStream(ctx context.Context, opts ...grpc.CallOption) (AgentService_FileUploadStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[5], "/agent.v1.AgentService/FileUploadStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentServiceFileUploadStreamClient{stream}
	return x, nil
}

type AgentService_FileUploadStreamClient interface {
	Send(*FileUploadRequest) error
	CloseAndRecv() (*FileUploadResponse, error)
	grpc.ClientStream
}

type agentServiceFileUploadStreamClient struct {
	grpc.ClientStream
}

func (x *agentServiceFileUploadStreamClient) Send(m *FileUploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentServiceFileUploadStreamClient) CloseAndRecv() (*FileUploadResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileUploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentServiceClient) NginxSiteApply(ctx context.Context, in *NginxSiteApplyRequest, opts ...grpc.CallOption) (*NginxSiteApplyResponse, error) {
	out := new(NginxSiteApplyResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/NginxSiteApply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallRule(ctx context.Context, in *FirewallRuleRequest, opts ...grpc.CallOption) (*FirewallRuleResponse, error) {
	out := new(FirewallRuleResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FirewallRule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallDelete(ctx context.Context, in *FirewallDeleteRequest, opts ...grpc.CallOption) (*FirewallDeleteResponse, error) {
	out := new(FirewallDeleteResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FirewallDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallList(ctx context.Context, in *FirewallListRequest, opts ...grpc.CallOption) (*FirewallListResponse, error) {
	out := new(FirewallListResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FirewallList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallStatus(ctx context.Context, in *FirewallStatusRequest, opts ...grpc.CallOption) (*FirewallStatusResponse, error) {
	out := new(FirewallStatusResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FirewallStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallToggle(ctx context.Context, in *FirewallToggleRequest, opts ...grpc.CallOption) (*FirewallToggleResponse, error) {
	out := new(FirewallToggleResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FirewallToggle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) FirewallReset(ctx context.Context, in *FirewallResetRequest, opts ...grpc.CallOption) (*FirewallResetResponse, error) {
	out := new(FirewallResetResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/FirewallReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SystemStats(ctx context.Context, in *SystemStatsRequest, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	out := new(SystemStatsResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/SystemStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/agent.v1.AgentService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility
type AgentServiceServer interface {
	// ── Systemd service management ─────────────────────────────────────────
	ServiceAction(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error)
	ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error)
	ServiceLogs(*ServiceLogsRequest, AgentService_ServiceLogsServer) error
	FileLogs(*FileLogsRequest, AgentService_FileLogsServer) error
	CommandExecute(context.Context, *CommandExecuteRequest) (*CommandExecuteResponse, error)
	// ── Package management ─────────────────────────────────────────────────
	PackageInstall(*PackageRequest, AgentService_PackageInstallServer) error
	PackageRemove(*PackageRequest, AgentService_PackageRemoveServer) error
	PackageUpdate(*PackageRequest, AgentService_PackageUpdateServer) error
	PackageStatus(context.Context, *PackageRequest) (*PackageStatusResponse, error)
	// ── File system ────────────────────────────────────────────────────────
	FileRead(context.Context, *FileReadRequest) (*FileReadResponse, error)
	FileWrite(context.Context, *FileWriteRequest) (*FileWriteResponse, error)
	FileDelete(context.Context, *FileDeleteRequest) (*FileDeleteResponse, error)
	DirCreate(context.Context, *DirCreateRequest) (*DirCreateResponse, error)
	DirList(context.Context, *DirListRequest) (*DirListResponse, error)
	FileRename(context.Context, *FileRenameRequest) (*FileRenameResponse, error)
	FileCopy(context.Context, *FileCopyRequest) (*FileCopyResponse, error)
	FileChmod(context.Context, *FileChmodRequest) (*FileChmodResponse, error)
	FileChown(context.Context, *FileChownRequest) (*FileChownResponse, error)
	ArchiveCreate(context.Context, *ArchiveCreateRequest) (*ArchiveCreateResponse, error)
	ArchiveExtract(context.Context, *ArchiveExtractRequest) (*ArchiveExtractResponse, error)
	FileUploadStream(AgentService_FileUploadStreamServer) error
	// Typed Nginx site configuration. The Agent renders, validates and applies
	// the configuration atomically; Core cannot execute arbitrary commands.
	NginxSiteApply(context.Context, *NginxSiteApplyRequest) (*NginxSiteApplyResponse, error)
	// ── Firewall ───────────────────────────────────────────────────────────
	FirewallRule(context.Context, *FirewallRuleRequest) (*FirewallRuleResponse, error)
	FirewallDelete(context.Context, *FirewallDeleteRequest) (*FirewallDeleteResponse, error)
	FirewallList(context.Context, *FirewallListRequest) (*FirewallListResponse, error)
	FirewallStatus(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error)
	FirewallToggle(context.Context, *FirewallToggleRequest) (*FirewallToggleResponse, error)
	FirewallReset(context.Context, *FirewallResetRequest) (*FirewallResetResponse, error)
	// ── System information ─────────────────────────────────────────────────
	SystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error)
	// ── Health check ───────────────────────────────────────────────────────
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServiceServer struct {
}

func (UnimplementedAgentServiceServer) ServiceAction(context.Context, *ServiceActionRequest) (*ServiceActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceAction not implemented")
}
func (UnimplementedAgentServiceServer) ServiceStatus(context.Context, *ServiceStatusRequest) (*ServiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServiceStatus not implemented")
}
func (UnimplementedAgentServiceServer) ServiceLogs(*ServiceLogsRequest, AgentService_ServiceLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method ServiceLogs not implemented")
}
func (UnimplementedAgentServiceServer) FileLogs(*FileLogsRequest, AgentService_FileLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method FileLogs not implemented")
}
func (UnimplementedAgentServiceServer) CommandExecute(context.Context, *CommandExecuteRequest) (*CommandExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommandExecute not implemented")
}
func (UnimplementedAgentServiceServer) PackageInstall(*PackageRequest, AgentService_PackageInstallServer) error {
	return status.Errorf(codes.Unimplemented, "method PackageInstall not implemented")
}
func (UnimplementedAgentServiceServer) PackageRemove(*PackageRequest, AgentService_PackageRemoveServer) error {
	return status.Errorf(codes.Unimplemented, "method PackageRemove not implemented")
}
func (UnimplementedAgentServiceServer) PackageUpdate(*PackageRequest, AgentService_PackageUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method PackageUpdate not implemented")
}
func (UnimplementedAgentServiceServer) PackageStatus(context.Context, *PackageRequest) (*PackageStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PackageStatus not implemented")
}
func (UnimplementedAgentServiceServer) FileRead(context.Context, *FileReadRequest) (*FileReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRead not implemented")
}
func (UnimplementedAgentServiceServer) FileWrite(context.Context, *FileWriteRequest) (*FileWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileWrite not implemented")
}
func (UnimplementedAgentServiceServer) FileDelete(context.Context, *FileDeleteRequest) (*FileDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileDelete not implemented")
}
func (UnimplementedAgentServiceServer) DirCreate(context.Context, *DirCreateRequest) (*DirCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DirCreate not implemented")
}
func (UnimplementedAgentServiceServer) DirList(context.Context, *DirListRequest) (*DirListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DirList not implemented")
}
func (UnimplementedAgentServiceServer) FileRename(context.Context, *FileRenameRequest) (*FileRenameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileRename not implemented")
}
func (UnimplementedAgentServiceServer) FileCopy(context.Context, *FileCopyRequest) (*FileCopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileCopy not implemented")
}
func (UnimplementedAgentServiceServer) FileChmod(context.Context, *FileChmodRequest) (*FileChmodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileChmod not implemented")
}
func (UnimplementedAgentServiceServer) FileChown(context.Context, *FileChownRequest) (*FileChownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileChown not implemented")
}
func (UnimplementedAgentServiceServer) ArchiveCreate(context.Context, *ArchiveCreateRequest) (*ArchiveCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveCreate not implemented")
}
func (UnimplementedAgentServiceServer) ArchiveExtract(context.Context, *ArchiveExtractRequest) (*ArchiveExtractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveExtract not implemented")
}
func (UnimplementedAgentServiceServer) FileUploadStream(AgentService_FileUploadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method FileUploadStream not implemented")
}
func (UnimplementedAgentServiceServer) NginxSiteApply(context.Context, *NginxSiteApplyRequest) (*NginxSiteApplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NginxSiteApply not implemented")
}
func (UnimplementedAgentServiceServer) FirewallRule(context.Context, *FirewallRuleRequest) (*FirewallRuleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirewallRule not implemented")
}
func (UnimplementedAgentServiceServer) FirewallDelete(context.Context, *FirewallDeleteRequest) (*FirewallDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirewallDelete not implemented")
}
func (UnimplementedAgentServiceServer) FirewallList(context.Context, *FirewallListRequest) (*FirewallListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirewallList not implemented")
}
func (UnimplementedAgentServiceServer) FirewallStatus(context.Context, *FirewallStatusRequest) (*FirewallStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirewallStatus not implemented")
}
func (UnimplementedAgentServiceServer) FirewallToggle(context.Context, *FirewallToggleRequest) (*FirewallToggleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirewallToggle not implemented")
}
func (UnimplementedAgentServiceServer) FirewallReset(context.Context, *FirewallResetRequest) (*FirewallResetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FirewallReset not implemented")
}
func (UnimplementedAgentServiceServer) SystemStats(context.Context, *SystemStatsRequest) (*SystemStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemStats not implemented")
}
func (UnimplementedAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ServiceAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ServiceAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/ServiceAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ServiceAction(ctx, req.(*ServiceActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/ServiceStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ServiceStatus(ctx, req.(*ServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ServiceLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServiceLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ServiceLogs(m, &agentServiceServiceLogsServer{stream})
}

type AgentService_ServiceLogsServer interface {
	Send(*LogLine) error
	grpc.ServerStream
}

type agentServiceServiceLogsServer struct {
	grpc.ServerStream
}

func (x *agentServiceServiceLogsServer) Send(m *LogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_FileLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FileLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).FileLogs(m, &agentServiceFileLogsServer{stream})
}

type AgentService_FileLogsServer interface {
	Send(*LogLine) error
	grpc.ServerStream
}

type agentServiceFileLogsServer struct {
	grpc.ServerStream
}

func (x *agentServiceFileLogsServer) Send(m *LogLine) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_CommandExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).CommandExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/CommandExecute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).CommandExecute(ctx, req.(*CommandExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_PackageInstall_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).PackageInstall(m, &agentServicePackageInstallServer{stream})
}

type AgentService_PackageInstallServer interface {
	Send(*PackageOutput) error
	grpc.ServerStream
}

type agentServicePackageInstallServer struct {
	grpc.ServerStream
}

func (x *agentServicePackageInstallServer) Send(m *PackageOutput) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_PackageRemove_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).PackageRemove(m, &agentServicePackageRemoveServer{stream})
}

type AgentService_PackageRemoveServer interface {
	Send(*PackageOutput) error
	grpc.ServerStream
}

type agentServicePackageRemoveServer struct {
	grpc.ServerStream
}

func (x *agentServicePackageRemoveServer) Send(m *PackageOutput) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_PackageUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PackageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).PackageUpdate(m, &agentServicePackageUpdateServer{stream})
}

type AgentService_PackageUpdateServer interface {
	Send(*PackageOutput) error
	grpc.ServerStream
}

type agentServicePackageUpdateServer struct {
	grpc.ServerStream
}

func (x *agentServicePackageUpdateServer) Send(m *PackageOutput) error {
	return x.ServerStream.SendMsg(m)
}

func _AgentService_PackageStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).PackageStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/PackageStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).PackageStatus(ctx, req.(*PackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FileRead",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileRead(ctx, req.(*FileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FileWrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileWrite(ctx, req.(*FileWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FileDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileDelete(ctx, req.(*FileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DirCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DirCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/DirCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DirCreate(ctx, req.(*DirCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DirList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DirListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DirList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/DirList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DirList(ctx, req.(*DirListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileRename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileRenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileRename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FileRename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileRename(ctx, req.(*FileRenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileCopy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileCopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileCopy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FileCopy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileCopy(ctx, req.(*FileCopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileChmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileChmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FileChmod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileChmod(ctx, req.(*FileChmodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileChown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileChownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FileChown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FileChown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FileChown(ctx, req.(*FileChownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ArchiveCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ArchiveCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/ArchiveCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ArchiveCreate(ctx, req.(*ArchiveCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ArchiveExtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ArchiveExtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/ArchiveExtract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ArchiveExtract(ctx, req.(*ArchiveExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FileUploadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).FileUploadStream(&agentServiceFileUploadStreamServer{stream})
}

type AgentService_FileUploadStreamServer interface {
	SendAndClose(*FileUploadResponse) error
	Recv() (*FileUploadRequest, error)
	grpc.ServerStream
}

type agentServiceFileUploadStreamServer struct {
	grpc.ServerStream
}

func (x *agentServiceFileUploadStreamServer) SendAndClose(m *FileUploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentServiceFileUploadStreamServer) Recv() (*FileUploadRequest, error) {
	m := new(FileUploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AgentService_NginxSiteApply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NginxSiteApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).NginxSiteApply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/NginxSiteApply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).NginxSiteApply(ctx, req.(*NginxSiteApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FirewallRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallRule(ctx, req.(*FirewallRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FirewallDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallDelete(ctx, req.(*FirewallDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FirewallList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallList(ctx, req.(*FirewallListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FirewallStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallStatus(ctx, req.(*FirewallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallToggle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallToggleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallToggle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FirewallToggle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallToggle(ctx, req.(*FirewallToggleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_FirewallReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirewallResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).FirewallReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/FirewallReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).FirewallReset(ctx, req.(*FirewallResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/SystemStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SystemStats(ctx, req.(*SystemStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.v1.AgentService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServiceAction",
			Handler:    _AgentService_ServiceAction_Handler,
		},
		{
			MethodName: "ServiceStatus",
			Handler:    _AgentService_ServiceStatus_Handler,
		},
		{
			MethodName: "CommandExecute",
			Handler:    _AgentService_CommandExecute_Handler,
		},
		{
			MethodName: "PackageStatus",
			Handler:    _AgentService_PackageStatus_Handler,
		},
		{
			MethodName: "FileRead",
			Handler:    _AgentService_FileRead_Handler,
		},
		{
			MethodName: "FileWrite",
			Handler:    _AgentService_FileWrite_Handler,
		},
		{
			MethodName: "FileDelete",
			Handler:    _AgentService_FileDelete_Handler,
		},
		{
			MethodName: "DirCreate",
			Handler:    _AgentService_DirCreate_Handler,
		},
		{
			MethodName: "DirList",
			Handler:    _AgentService_DirList_Handler,
		},
		{
			MethodName: "FileRename",
			Handler:    _AgentService_FileRename_Handler,
		},
		{
			MethodName: "FileCopy",
			Handler:    _AgentService_FileCopy_Handler,
		},
		{
			MethodName: "FileChmod",
			Handler:    _AgentService_FileChmod_Handler,
		},
		{
			MethodName: "FileChown",
			Handler:    _AgentService_FileChown_Handler,
		},
		{
			MethodName: "ArchiveCreate",
			Handler:    _AgentService_ArchiveCreate_Handler,
		},
		{
			MethodName: "ArchiveExtract",
			Handler:    _AgentService_ArchiveExtract_Handler,
		},
		{
			MethodName: "NginxSiteApply",
			Handler:    _AgentService_NginxSiteApply_Handler,
		},
		{
			MethodName: "FirewallRule",
			Handler:    _AgentService_FirewallRule_Handler,
		},
		{
			MethodName: "FirewallDelete",
			Handler:    _AgentService_FirewallDelete_Handler,
		},
		{
			MethodName: "FirewallList",
			Handler:    _AgentService_FirewallList_Handler,
		},
		{
			MethodName: "FirewallStatus",
			Handler:    _AgentService_FirewallStatus_Handler,
		},
		{
			MethodName: "FirewallToggle",
			Handler:    _AgentService_FirewallToggle_Handler,
		},
		{
			MethodName: "FirewallReset",
			Handler:    _AgentService_FirewallReset_Handler,
		},
		{
			MethodName: "SystemStats",
			Handler:    _AgentService_SystemStats_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServiceLogs",
			Handler:       _AgentService_ServiceLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileLogs",
			Handler:       _AgentService_FileLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PackageInstall",
			Handler:       _AgentService_PackageInstall_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PackageRemove",
			Handler:       _AgentService_PackageRemove_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PackageUpdate",
			Handler:       _AgentService_PackageUpdate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FileUploadStream",
			Handler:       _AgentService_FileUploadStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/v1/agent.proto",
}
