name: Nightly Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  nightly:
    uses: ./.github/workflows/build-binaries.yml
    with:
      version: "nightly"
      release_tag: "nightly"
      prerelease: true
      generate_release_notes: false
